//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v10
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteFiguraTransportePropietarioDomicilio", Namespace="http://www.sat.gob.mx/CartaPorte", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class CartaPorteFiguraTransportePropietarioDomicilio
    {
        
        /// <summary>
        /// <para>Atributo requerido que sirve para precisar la calle en que está ubicado el domicilio del propietario del medio de transporte.</para>
        /// <para>Tipo definido para expresar la calle en que está ubicado el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,100}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido que sirve para precisar la calle en que está ubicado el domici" +
            "lio del propietario del medio de transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(100)]
        [RegularExpressionAttribute("[^|]{1,100}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Calle")]
        public string Calle { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional que sirve para expresar el número exterior en donde se ubica el domicilio del propietario del transporte.</para>
        /// <para>Tipo definido para expresar el número interior o el número exterior en donde se ubica el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 55.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,55}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional que sirve para expresar el número exterior en donde se ubica el" +
            " domicilio del propietario del transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(55)]
        [RegularExpressionAttribute("[^|]{1,55}")]
        [XmlAttributeAttribute("NumeroExterior")]
        public string NumeroExterior { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional que sirve para expresar el número interior, en caso de existir, en donde se ubica el domicilio del propietario del transporte.</para>
        /// <para>Tipo definido para expresar el número interior o el número exterior en donde se ubica el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 55.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,55}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional que sirve para expresar el número interior, en caso de existir," +
            " en donde se ubica el domicilio del propietario del transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(55)]
        [RegularExpressionAttribute("[^|]{1,55}")]
        [XmlAttributeAttribute("NumeroInterior")]
        public string NumeroInterior { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional que sirve para expresar la clave de la colonia o dato análogo en donde se ubica el domicilio del propietario del transporte.</para>
        /// <para>Tipo definido para expresar la colonia, localidad o municipio en que está ubicado el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 120.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,120}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional que sirve para expresar la clave de la colonia o dato análogo e" +
            "n donde se ubica el domicilio del propietario del transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(120)]
        [RegularExpressionAttribute("[^|]{1,120}")]
        [XmlAttributeAttribute("Colonia")]
        public string Colonia { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para precisar la clave de la ciudad, población, distrito u análogo en donde se encuentra ubicado el domicilio del propietario del transporte.</para>
        /// <para>Tipo definido para expresar la colonia, localidad o municipio en que está ubicado el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 120.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,120}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para precisar la clave de la ciudad, población, distrito u anál" +
            "ogo en donde se encuentra ubicado el domicilio del propietario del transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(120)]
        [RegularExpressionAttribute("[^|]{1,120}")]
        [XmlAttributeAttribute("Localidad")]
        public string Localidad { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para expresar una referencia geográfica adicional que permita una más fácil o precisa ubicación del propietario del transporte; por ejemplo, las coordenadas GPS.</para>
        /// <para>Tipo definido para expresar la referencia geográfica adicional que permita una  fácil o precisa ubicación del domicilio del emisor del comprobante o del destinatario de la mercancía, por ejemplo las coordenadas GPS.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 250.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,250}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para expresar una referencia geográfica adicional que permita u" +
            "na más fácil o precisa ubicación del propietario del transporte; por ejemplo, la" +
            "s coordenadas GPS.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(250)]
        [RegularExpressionAttribute("[^|]{1,250}")]
        [XmlAttributeAttribute("Referencia")]
        public string Referencia { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para precisar la clave del municipio, delegación o alcaldía, condado u otro análogo en donde se encuentra ubicado el domicilio del propietario del transporte.</para>
        /// <para>Tipo definido para expresar la colonia, localidad o municipio en que está ubicado el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 120.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,120}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para precisar la clave del municipio, delegación o alcaldía, co" +
            "ndado u otro análogo en donde se encuentra ubicado el domicilio del propietario " +
            "del transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(120)]
        [RegularExpressionAttribute("[^|]{1,120}")]
        [XmlAttributeAttribute("Municipio")]
        public string Municipio { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para precisar el estado, entidad, región, comunidad, u otra figura análoga en donde se encuentra ubicado el domicilio del propietario del transporte.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,30}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para precisar el estado, entidad, región, comunidad, u otra fi" +
            "gura análoga en donde se encuentra ubicado el domicilio del propietario del tran" +
            "sporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(30)]
        [RegularExpressionAttribute("[^|]{1,30}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Estado")]
        public string Estado { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido que sirve para precisar la clave del país en donde se encuentra ubicado el domicilio del propietario del transporte, conforme al catálogo c_Pais publicado en el portal del SAT en Internet que está basado en la especificación ISO 3166-1.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido que sirve para precisar la clave del país en donde se encuentr" +
            "a ubicado el domicilio del propietario del transporte, conforme al catálogo c_Pa" +
            "is publicado en el portal del SAT en Internet que está basado en la especificaci" +
            "ón ISO 3166-1.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Pais")]
        public string Pais { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para asentar el código postal (PO, BOX) en donde se encuentra ubicado el domicilio del propietario del transporte.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 12.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para asentar el código postal (PO, BOX) en donde se encuentra " +
            "ubicado el domicilio del propietario del transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(12)]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("CodigoPostal")]
        public string CodigoPostal { get; set; }
    }
}
