//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v10
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteMercanciasTransporteFerroviarioDerechosDePaso", Namespace="http://www.sat.gob.mx/CartaPorte", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("CartaPorteMercanciasTransporteFerroviarioDerechosDePaso", Namespace="http://www.sat.gob.mx/CartaPorte")]
    public partial class CartaPorteMercanciasTransporteFerroviarioDerechosDePaso
    {
        
        /// <summary>
        /// <para>Atributo requerido para registrar el valor de la clave del derecho de paso pagado por el transportista en las vías férreas de las cuales no es concesionario o asignatario.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar el valor de la clave del derecho de paso pagado" +
            " por el transportista en las vías férreas de las cuales no es concesionario o as" +
            "ignatario.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TipoDerechoDePaso")]
        public string TipoDerechoDePaso { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar el total de kilómetros pagados por el transportista en las vías férreas de las cuales no es concesionario o asignatario con el derecho de paso.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.01.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar el total de kilómetros pagados por el transport" +
            "ista en las vías férreas de las cuales no es concesionario o asignatario con el " +
            "derecho de paso.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("KilometrajePagado")]
        public decimal KilometrajePagado { get; set; }
    }
}
