//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v10
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteMercanciasAutotransporteFederalRemolques", Namespace="http://www.sat.gob.mx/CartaPorte", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class CartaPorteMercanciasAutotransporteFederalRemolques
    {
        
        [XmlIgnoreAttribute()]
        private Collection<CartaPorteMercanciasAutotransporteFederalRemolquesRemolque> _remolque;
        
        /// <summary>
        /// <para>Nodo requerido para expresar la información del remolque o semirremolques que se emplean con el autotransporte para el traslado de los bienes o mercancías.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para expresar la información del remolque o semirremolques que se " +
            "emplean con el autotransporte para el traslado de los bienes o mercancías.")]
        [XmlElementAttribute("Remolque")]
        public Collection<CartaPorteMercanciasAutotransporteFederalRemolquesRemolque> Remolque
        {
            get
            {
                return _remolque;
            }
            private set
            {
                _remolque = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Remolque collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool RemolqueSpecified
        {
            get
            {
                return (this.Remolque.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CartaPorteMercanciasAutotransporteFederalRemolques" /> class.</para>
        /// </summary>
        public CartaPorteMercanciasAutotransporteFederalRemolques()
        {
            this._remolque = new Collection<CartaPorteMercanciasAutotransporteFederalRemolquesRemolque>();
        }
    }
}
