//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v10
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteFiguraTransportePropietario", Namespace="http://www.sat.gob.mx/CartaPorte", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class CartaPorteFiguraTransportePropietario
    {
        
        /// <summary>
        /// <para>Nodo opcional para registrar el domicilio del propietario para el traslado de la mercancía.</para>
        /// </summary>
        [DescriptionAttribute("Nodo opcional para registrar el domicilio del propietario para el traslado de la " +
            "mercancía.")]
        [XmlElementAttribute("Domicilio")]
        public CartaPorteFiguraTransportePropietarioDomicilio Domicilio { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar el RFC del propietario del medio de transporte.</para>
        /// <para>Tipo definido para expresar claves del Registro Federal de Contribuyentes</para>
        /// <para xml:lang="en">Minimum length: 12.</para>
        /// <para xml:lang="en">Maximum length: 13.</para>
        /// <para xml:lang="en">Pattern: [A-Z&Ñ]{3,4}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A].</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar el RFC del propietario del medio de transport" +
            "e.")]
        [MinLengthAttribute(12)]
        [MaxLengthAttribute(13)]
        [RegularExpressionAttribute("[A-Z&Ñ]{3,4}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A]")]
        [XmlAttributeAttribute("RFCPropietario")]
        public string RfcPropietario { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar el nombre del propietario del medio de transporte.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 254.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,254}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para registrar el nombre del propietario del medio de transport" +
            "e.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(254)]
        [RegularExpressionAttribute("[^|]{1,254}")]
        [XmlAttributeAttribute("NombrePropietario")]
        public string NombrePropietario { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para incorporar el número de identificación o registro fiscal del país de residencia para los efectos fiscales del propietario del transporte, cuando sea residente en el extranjero.</para>
        /// <para xml:lang="en">Minimum length: 6.</para>
        /// <para xml:lang="en">Maximum length: 40.</para>
        /// <para xml:lang="en">Pattern: [^|]{6,40}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para incorporar el número de identificación o registro fisca" +
            "l del país de residencia para los efectos fiscales del propietario del transport" +
            "e, cuando sea residente en el extranjero.")]
        [MinLengthAttribute(6)]
        [MaxLengthAttribute(40)]
        [RegularExpressionAttribute("[^|]{6,40}")]
        [XmlAttributeAttribute("NumRegIdTribPropietario")]
        public string NumRegIdTribPropietario { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar la clave del país de residencia para efectos fiscales del propietario del transporte, conforme con el catálogo c_Pais publicado en el portal del SAT en Internet que está basado en la especificación ISO 3166-1.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar la clave del país de residencia para efectos " +
            "fiscales del propietario del transporte, conforme con el catálogo c_Pais publica" +
            "do en el portal del SAT en Internet que está basado en la especificación ISO 316" +
            "6-1.")]
        [XmlAttributeAttribute("ResidenciaFiscalPropietario")]
        public string ResidenciaFiscalPropietario { get; set; }
    }
}
