//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v10
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteFiguraTransporteOperadores", Namespace="http://www.sat.gob.mx/CartaPorte", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class CartaPorteFiguraTransporteOperadores
    {
        
        [XmlIgnoreAttribute()]
        private Collection<CartaPorteFiguraTransporteOperadoresOperador> _operador;
        
        /// <summary>
        /// <para>Nodo requerido para indicar los datos del operador del autotransporte de carga federal en el que se trasladan los bienes o mercancías.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para indicar los datos del operador del autotransporte de carga fe" +
            "deral en el que se trasladan los bienes o mercancías.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Operador")]
        public Collection<CartaPorteFiguraTransporteOperadoresOperador> Operador
        {
            get
            {
                return _operador;
            }
            private set
            {
                _operador = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CartaPorteFiguraTransporteOperadores" /> class.</para>
        /// </summary>
        public CartaPorteFiguraTransporteOperadores()
        {
            this._operador = new Collection<CartaPorteFiguraTransporteOperadoresOperador>();
        }
    }
}
