//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v10
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Complemento para incorporar al Comprobante Fiscal Digital por Internet (CFDI), la información relacionada a los bienes o mercancías, ubicaciones de origen, puntos intermedios y destino, así como lo referente al medio por el que se transportan; ya sea por vía terrestre (carretera federal o líneas férreas), aérea, marítima o fluvial; además de incluir el traslado de Hidrocarburos y Petrolíferos.</para>
    /// </summary>
    [DescriptionAttribute(@"Complemento para incorporar al Comprobante Fiscal Digital por Internet (CFDI), la información relacionada a los bienes o mercancías, ubicaciones de origen, puntos intermedios y destino, así como lo referente al medio por el que se transportan; ya sea por vía terrestre (carretera federal o líneas férreas), aérea, marítima o fluvial; además de incluir el traslado de Hidrocarburos y Petrolíferos.")]
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorte", Namespace="http://www.sat.gob.mx/CartaPorte", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("CartaPorte", Namespace="http://www.sat.gob.mx/CartaPorte")]
    public partial class CartaPorte
    {
        
        [XmlIgnoreAttribute()]
        private Collection<CartaPorteUbicacionesUbicacion> _ubicaciones;
        
        /// <summary>
        /// <para>Nodo requerido para registrar las distintas ubicaciones que sirven para reflejar el domicilio del origen y/o destino que tienen los bienes o mercancías que se trasladan por distintos medios de transporte.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para registrar las distintas ubicaciones que sirven para reflejar " +
            "el domicilio del origen y/o destino que tienen los bienes o mercancías que se tr" +
            "asladan por distintos medios de transporte.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlArrayAttribute("Ubicaciones")]
        [XmlArrayItemAttribute("Ubicacion", Namespace="http://www.sat.gob.mx/CartaPorte")]
        public Collection<CartaPorteUbicacionesUbicacion> Ubicaciones
        {
            get
            {
                return _ubicaciones;
            }
            private set
            {
                _ubicaciones = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CartaPorte" /> class.</para>
        /// </summary>
        public CartaPorte()
        {
            this._ubicaciones = new Collection<CartaPorteUbicacionesUbicacion>();
        }
        
        /// <summary>
        /// <para>Nodo requerido para registrar la información de los bienes o mercancías que se trasladan en los distintos medios de transporte.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para registrar la información de los bienes o mercancías que se tr" +
            "asladan en los distintos medios de transporte.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Mercancias")]
        public CartaPorteMercancias Mercancias { get; set; }
        
        /// <summary>
        /// <para>Nodo opcional para indicar los datos de la figura del transporte que interviene en el traslado de los bienes o mercancías, cuando el dueño del medio de transporte es diferente del emisor del comprobante con el complemento carta porte.</para>
        /// </summary>
        [DescriptionAttribute("Nodo opcional para indicar los datos de la figura del transporte que interviene e" +
            "n el traslado de los bienes o mercancías, cuando el dueño del medio de transport" +
            "e es diferente del emisor del comprobante con el complemento carta porte.")]
        [XmlElementAttribute("FiguraTransporte")]
        public CartaPorteFiguraTransporte FiguraTransporte { get; set; }
        
        [XmlIgnoreAttribute()]
        private string _version = "1.0";
        
        /// <summary>
        /// <para>Atributo requerido con valor prefijado que indica la versión del complemento Carta Porte.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido con valor prefijado que indica la versión del complemento Cart" +
            "a Porte.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
        
        /// <summary>
        /// <para>Atributo requerido para expresar si los bienes o mercancías que son transportadas ingresan o salen del territorio nacional.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar si los bienes o mercancías que son transportadas" +
            " ingresan o salen del territorio nacional.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TranspInternac")]
        public string TranspInternac { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para precisar si los bienes o mercancías ingresan o salen del territorio nacional.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para precisar si los bienes o mercancías ingresan o salen de" +
            "l territorio nacional.")]
        [XmlAttributeAttribute("EntradaSalidaMerc")]
        public string EntradaSalidaMerc { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para precisar la vía de ingreso o salida de los bienes o mercancías en territorio nacional.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para precisar la vía de ingreso o salida de los bienes o mer" +
            "cancías en territorio nacional.")]
        [XmlAttributeAttribute("ViaEntradaSalida")]
        public string ViaEntradaSalida { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar la suma de las distancias recorridas en kilómetros, registradas en el atributo “Ubicaciones:Ubicacion:DistanciaRecorrida” para el traslado de los bienes o mercancías.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.01.</para>
        /// <para xml:lang="en">Maximum inclusive value: 99999.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar la suma de las distancias recorridas en kilóm" +
            "etros, registradas en el atributo “Ubicaciones:Ubicacion:DistanciaRecorrida” par" +
            "a el traslado de los bienes o mercancías.")]
        [RangeAttribute(typeof(decimal), "0.01", "99999", ParseLimitsInInvariantCulture=true, ConvertValueInInvariantCulture=true)]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("TotalDistRec")]
        public decimal TotalDistRecValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TotalDistRec property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool TotalDistRecValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar la suma de las distancias recorridas en kilómetros, registradas en el atributo “Ubicaciones:Ubicacion:DistanciaRecorrida” para el traslado de los bienes o mercancías.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.01.</para>
        /// <para xml:lang="en">Maximum inclusive value: 99999.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<decimal> TotalDistRec
        {
            get
            {
                if (this.TotalDistRecValueSpecified)
                {
                    return this.TotalDistRecValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TotalDistRecValue = value.GetValueOrDefault();
                this.TotalDistRecValueSpecified = value.HasValue;
            }
        }
    }
}
