//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v10
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteMercanciasMercanciaDetalleMercancia", Namespace="http://www.sat.gob.mx/CartaPorte", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("CartaPorteMercanciasMercanciaDetalleMercancia", Namespace="http://www.sat.gob.mx/CartaPorte")]
    public partial class CartaPorteMercanciasMercanciaDetalleMercancia
    {
        
        /// <summary>
        /// <para>Atributo requerido para expresar la clave de unidad de medida estandarizada del peso de los bienes o mercancías que se trasladan.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar la clave de unidad de medida estandarizada del p" +
            "eso de los bienes o mercancías que se trasladan.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("UnidadPeso")]
        public string UnidadPeso { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el peso total bruto de los bienes o mercancías que se trasladan.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 3.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.001.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el peso total bruto de los bienes o mercancías q" +
            "ue se trasladan.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("PesoBruto")]
        public decimal PesoBruto { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el peso total neto de los bienes o mercancías que se trasladan.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 3.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.001.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el peso total neto de los bienes o mercancías qu" +
            "e se trasladan.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("PesoNeto")]
        public decimal PesoNeto { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el peso bruto, menos el peso neto de las mercancías que se trasladan.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 3.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.001.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el peso bruto, menos el peso neto de las mercanc" +
            "ías que se trasladan.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("PesoTara")]
        public decimal PesoTara { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar el número de piezas de los bienes o mercancías que se trasladan.</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para registrar el número de piezas de los bienes o mercancías q" +
            "ue se trasladan.")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("NumPiezas")]
        public int NumPiezasValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the NumPiezas property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool NumPiezasValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar el número de piezas de los bienes o mercancías que se trasladan.</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<int> NumPiezas
        {
            get
            {
                if (this.NumPiezasValueSpecified)
                {
                    return this.NumPiezasValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.NumPiezasValue = value.GetValueOrDefault();
                this.NumPiezasValueSpecified = value.HasValue;
            }
        }
    }
}
