//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/TimbreFiscalDigital=TFD.v1 resources/sitio_internet/cfd/TimbreFiscalDigital/TimbreFiscalDigital.xsd
namespace JAMS.SAT.CFDI.Xml.TFD.v1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Complemento requerido para el Timbrado Fiscal Digital que da valides a un Comprobante Fiscal Digital.</para>
    /// </summary>
    [DescriptionAttribute("Complemento requerido para el Timbrado Fiscal Digital que da valides a un Comprob" +
        "ante Fiscal Digital.")]
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("TimbreFiscalDigital", Namespace="http://www.sat.gob.mx/TimbreFiscalDigital", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("TimbreFiscalDigital", Namespace="http://www.sat.gob.mx/TimbreFiscalDigital")]
    public partial class TimbreFiscalDigital
    {
        
        [XmlIgnoreAttribute()]
        private string _version = "1.0";
        
        /// <summary>
        /// <para>Atributo requerido para la expresión de la versión del estándar del Timbre Fiscal Digital</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para la expresión de la versión del estándar del Timbre Fiscal" +
            " Digital")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
        
        /// <summary>
        /// <para>Atributo requerido para expresar los 36 caracteres del UUID de la transacción de timbrado</para>
        /// <para xml:lang="en">Minimum length: 36.</para>
        /// <para xml:lang="en">Maximum length: 36.</para>
        /// <para xml:lang="en">Pattern: [a-f0-9A-F]{8}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{12}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar los 36 caracteres del UUID de la transacción de " +
            "timbrado")]
        [MinLengthAttribute(36)]
        [MaxLengthAttribute(36)]
        [RegularExpressionAttribute("[a-f0-9A-F]{8}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{12}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("UUID")]
        public string Uuid { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar la fecha y hora de la generación del timbre</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar la fecha y hora de la generación del timbre")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("FechaTimbrado", DataType="dateTime")]
        public DateTime FechaTimbrado { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para contener el sello digital del comprobante fiscal, que será timbrado. El sello deberá ser expresado cómo una cadena de texto en formato Base 64.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para contener el sello digital del comprobante fiscal, que ser" +
            "á timbrado. El sello deberá ser expresado cómo una cadena de texto en formato Ba" +
            "se 64.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("selloCFD")]
        public string SelloCfd { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el número de serie del certificado del SAT usado para el Timbre</para>
        /// <para xml:lang="en">Minimum length: 20.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el número de serie del certificado del SAT usado" +
            " para el Timbre")]
        [MinLengthAttribute(20)]
        [MaxLengthAttribute(20)]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("noCertificadoSAT")]
        public string NoCertificadoSat { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para contener el sello digital del Timbre Fiscal Digital, al que hacen referencia las reglas de resolución miscelánea aplicable. El sello deberá ser expresado cómo una cadena de texto en formato Base 64.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para contener el sello digital del Timbre Fiscal Digital, al q" +
            "ue hacen referencia las reglas de resolución miscelánea aplicable. El sello debe" +
            "rá ser expresado cómo una cadena de texto en formato Base 64.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("selloSAT")]
        public string SelloSat { get; set; }
    }
}
