//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v30
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteFiguraTransporteTiposFigura", Namespace="http://www.sat.gob.mx/CartaPorte30", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("CartaPorteFiguraTransporteTiposFigura", Namespace="http://www.sat.gob.mx/CartaPorte30")]
    public partial class CartaPorteFiguraTransporteTiposFigura
    {
        
        [XmlIgnoreAttribute()]
        private Collection<CartaPorteFiguraTransporteTiposFiguraPartesTransporte> _partesTransporte;
        
        /// <summary>
        /// <para>Nodo condicional para indicar los datos de las partes del transporte de las cuales el emisor del comprobante es distinto al dueño de las mismas, por ejemplo: vehículos, máquinas, contenedores, plataformas, entre otros, etc; mismos que son utilizados para el traslado de los bienes y/o mercancías.</para>
        /// </summary>
        [DescriptionAttribute(@"Nodo condicional para indicar los datos de las partes del transporte de las cuales el emisor del comprobante es distinto al dueño de las mismas, por ejemplo: vehículos, máquinas, contenedores, plataformas, entre otros, etc; mismos que son utilizados para el traslado de los bienes y/o mercancías.")]
        [XmlElementAttribute("PartesTransporte")]
        public Collection<CartaPorteFiguraTransporteTiposFiguraPartesTransporte> PartesTransporte
        {
            get
            {
                return _partesTransporte;
            }
            private set
            {
                _partesTransporte = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the PartesTransporte collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool PartesTransporteSpecified
        {
            get
            {
                return (this.PartesTransporte.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CartaPorteFiguraTransporteTiposFigura" /> class.</para>
        /// </summary>
        public CartaPorteFiguraTransporteTiposFigura()
        {
            this._partesTransporte = new Collection<CartaPorteFiguraTransporteTiposFiguraPartesTransporte>();
        }
        
        /// <summary>
        /// <para>Nodo opcional para registrar información del domicilio del(los) tipo(s) de figura transporte que intervenga(n) en el traslado de los bienes y/o mercancías.</para>
        /// </summary>
        [DescriptionAttribute("Nodo opcional para registrar información del domicilio del(los) tipo(s) de figura" +
            " transporte que intervenga(n) en el traslado de los bienes y/o mercancías.")]
        [XmlElementAttribute("Domicilio")]
        public CartaPorteFiguraTransporteTiposFiguraDomicilio Domicilio { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar la clave de la figura de transporte que interviene en el traslado de los bienes y/o mercancías.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar la clave de la figura de transporte que intervi" +
            "ene en el traslado de los bienes y/o mercancías.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TipoFigura")]
        public string TipoFigura { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar el RFC de la figura de transporte que interviene en el traslado de los bienes y/o mercancías.</para>
        /// <para xml:lang="en">Minimum length: 12.</para>
        /// <para xml:lang="en">Maximum length: 13.</para>
        /// <para xml:lang="en">Pattern: [A-Z&Ñ]{3,4}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A].</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar el RFC de la figura de transporte que intervi" +
            "ene en el traslado de los bienes y/o mercancías.")]
        [MinLengthAttribute(12)]
        [MaxLengthAttribute(13)]
        [RegularExpressionAttribute("[A-Z&Ñ]{3,4}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A]")]
        [XmlAttributeAttribute("RFCFigura")]
        public string RfcFigura { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el número de la licencia o el permiso otorgado al operador del autotransporte de carga en el que realiza el traslado de los bienes y/o mercancías.</para>
        /// <para xml:lang="en">Minimum length: 6.</para>
        /// <para xml:lang="en">Maximum length: 16.</para>
        /// <para xml:lang="en">Pattern: [^|]{6,16}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar el número de la licencia o el permiso otorgado" +
            " al operador del autotransporte de carga en el que realiza el traslado de los bi" +
            "enes y/o mercancías.")]
        [MinLengthAttribute(6)]
        [MaxLengthAttribute(16)]
        [RegularExpressionAttribute("[^|]{6,16}")]
        [XmlAttributeAttribute("NumLicencia")]
        public string NumLicencia { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar el nombre de la figura de transporte que interviene en el traslado de los bienes y/o mercancías.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 254.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,254}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar el nombre de la figura de transporte que interv" +
            "iene en el traslado de los bienes y/o mercancías.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(254)]
        [RegularExpressionAttribute("[^|]{1,254}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("NombreFigura")]
        public string NombreFigura { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar el número de identificación o registro fiscal del país de residencia de la figura de transporte que interviene en el traslado de los bienes y/o mercancías, cuando se trate de residentes en el extranjero para los efectos fiscales correspondientes.</para>
        /// <para xml:lang="en">Minimum length: 6.</para>
        /// <para xml:lang="en">Maximum length: 40.</para>
        /// <para xml:lang="en">Pattern: [^|]{6,40}.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para registrar el número de identificación o registro fiscal del país de residencia de la figura de transporte que interviene en el traslado de los bienes y/o mercancías, cuando se trate de residentes en el extranjero para los efectos fiscales correspondientes.")]
        [MinLengthAttribute(6)]
        [MaxLengthAttribute(40)]
        [RegularExpressionAttribute("[^|]{6,40}")]
        [XmlAttributeAttribute("NumRegIdTribFigura")]
        public string NumRegIdTribFigura { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar la clave del país de residencia de la figura de transporte que interviene en el traslado de los bienes y/o mercancías para los efectos fiscales correspondientes.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar la clave del país de residencia de la figura " +
            "de transporte que interviene en el traslado de los bienes y/o mercancías para lo" +
            "s efectos fiscales correspondientes.")]
        [XmlAttributeAttribute("ResidenciaFiscalFigura")]
        public string ResidenciaFiscalFigura { get; set; }
    }
}
