//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v30
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteFiguraTransporteTiposFiguraDomicilio", Namespace="http://www.sat.gob.mx/CartaPorte30", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("CartaPorteFiguraTransporteTiposFiguraDomicilio", Namespace="http://www.sat.gob.mx/CartaPorte30")]
    public partial class CartaPorteFiguraTransporteTiposFiguraDomicilio
    {
        
        /// <summary>
        /// <para>Atributo opcional que sirve para registrar la calle en la que está ubicado el domicilio del(los) tipo(s) de figura transporte.</para>
        /// <para>Tipo definido para expresar la calle en que está ubicado el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,100}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional que sirve para registrar la calle en la que está ubicado el dom" +
            "icilio del(los) tipo(s) de figura transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(100)]
        [RegularExpressionAttribute("[^|]{1,100}")]
        [XmlAttributeAttribute("Calle")]
        public string Calle { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional que sirve para registrar el número exterior en donde se ubica el domicilio del(los) tipo(s) de figura transporte.</para>
        /// <para>Tipo definido para expresar el número interior o el número exterior en donde se ubica el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 55.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,55}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional que sirve para registrar el número exterior en donde se ubica e" +
            "l domicilio del(los) tipo(s) de figura transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(55)]
        [RegularExpressionAttribute("[^|]{1,55}")]
        [XmlAttributeAttribute("NumeroExterior")]
        public string NumeroExterior { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional que sirve para registrar el número interior, en caso de existir, en donde se ubica el domicilio del(los) tipo(s) de figura transporte.</para>
        /// <para>Tipo definido para expresar el número interior o el número exterior en donde se ubica el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 55.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,55}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional que sirve para registrar el número interior, en caso de existir" +
            ", en donde se ubica el domicilio del(los) tipo(s) de figura transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(55)]
        [RegularExpressionAttribute("[^|]{1,55}")]
        [XmlAttributeAttribute("NumeroInterior")]
        public string NumeroInterior { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional que sirve para expresar la clave de la colonia o dato análogo en donde se ubica el domicilio del(los) tipo(s) de figura transporte.</para>
        /// <para>Tipo definido para expresar la colonia, localidad o municipio en que está ubicado el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 120.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,120}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional que sirve para expresar la clave de la colonia o dato análogo e" +
            "n donde se ubica el domicilio del(los) tipo(s) de figura transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(120)]
        [RegularExpressionAttribute("[^|]{1,120}")]
        [XmlAttributeAttribute("Colonia")]
        public string Colonia { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar la clave de la ciudad, población, distrito o dato análogo de donde se encuentra ubicado el domicilio del(los) tipo(s) de figura transporte.</para>
        /// <para>Tipo definido para expresar la colonia, localidad o municipio en que está ubicado el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 120.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,120}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para registrar la clave de la ciudad, población, distrito o dat" +
            "o análogo de donde se encuentra ubicado el domicilio del(los) tipo(s) de figura " +
            "transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(120)]
        [RegularExpressionAttribute("[^|]{1,120}")]
        [XmlAttributeAttribute("Localidad")]
        public string Localidad { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar una referencia geográfica adicional que permita una fácil o precisa ubicación del domicilio del(los) tipo(s) de figura transporte; por ejemplo, las coordenadas del GPS.</para>
        /// <para>Tipo definido para expresar la referencia geográfica adicional que permita una  fácil o precisa ubicación del domicilio del emisor del comprobante o del destinatario de la mercancía, por ejemplo las coordenadas GPS.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 250.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,250}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para registrar una referencia geográfica adicional que permita " +
            "una fácil o precisa ubicación del domicilio del(los) tipo(s) de figura transport" +
            "e; por ejemplo, las coordenadas del GPS.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(250)]
        [RegularExpressionAttribute("[^|]{1,250}")]
        [XmlAttributeAttribute("Referencia")]
        public string Referencia { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar la clave del municipio, delegación o alcaldía, condado o dato análogo en donde se encuentra ubicado el domicilio del(los) tipo(s) de figura transporte.</para>
        /// <para>Tipo definido para expresar la colonia, localidad o municipio en que está ubicado el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 120.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,120}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para registrar la clave del municipio, delegación o alcaldía, c" +
            "ondado o dato análogo en donde se encuentra ubicado el domicilio del(los) tipo(s" +
            ") de figura transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(120)]
        [RegularExpressionAttribute("[^|]{1,120}")]
        [XmlAttributeAttribute("Municipio")]
        public string Municipio { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar el estado, entidad, región, comunidad, o dato análogo en donde se encuentra ubicado el domicilio del(los) tipo(s) de figura transporte.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,30}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar el estado, entidad, región, comunidad, o dato a" +
            "nálogo en donde se encuentra ubicado el domicilio del(los) tipo(s) de figura tra" +
            "nsporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(30)]
        [RegularExpressionAttribute("[^|]{1,30}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Estado")]
        public string Estado { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido que sirve para registrar la clave del país en donde se encuentra ubicado el domicilio del(los) tipo(s) de figura transporte, conforme al catálogo c_Pais del CFDI publicado en el portal del SAT en Internet de acuerdo a la especificación ISO 3166-1.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo requerido que sirve para registrar la clave del país en donde se encuentra ubicado el domicilio del(los) tipo(s) de figura transporte, conforme al catálogo c_Pais del CFDI publicado en el portal del SAT en Internet de acuerdo a la especificación ISO 3166-1.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Pais")]
        public string Pais { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar el código postal en donde se encuentra ubicado el domicilio del(los) tipo(s) de figura transporte.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 12.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar el código postal en donde se encuentra ubicado " +
            "el domicilio del(los) tipo(s) de figura transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(12)]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("CodigoPostal")]
        public string CodigoPostal { get; set; }
    }
}
