//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v30
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteMercanciasAutotransporte", Namespace="http://www.sat.gob.mx/CartaPorte30", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("CartaPorteMercanciasAutotransporte", Namespace="http://www.sat.gob.mx/CartaPorte30")]
    public partial class CartaPorteMercanciasAutotransporte
    {
        
        /// <summary>
        /// <para>Nodo requerido para registrar los datos de identificación del autotransporte en el que se trasladan los bienes y/o mercancías.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para registrar los datos de identificación del autotransporte en e" +
            "l que se trasladan los bienes y/o mercancías.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("IdentificacionVehicular")]
        public CartaPorteMercanciasAutotransporteIdentificacionVehicular IdentificacionVehicular { get; set; }
        
        /// <summary>
        /// <para>Nodo requerido para registrar los datos de las pólizas de seguro que cubren los riesgos en el traslado de los bienes y/o mercancías.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para registrar los datos de las pólizas de seguro que cubren los r" +
            "iesgos en el traslado de los bienes y/o mercancías.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Seguros")]
        public CartaPorteMercanciasAutotransporteSeguros Seguros { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<CartaPorteMercanciasAutotransporteRemolquesRemolque> _remolques;
        
        /// <summary>
        /// <para>Nodo condicional para registrar los datos del(los) remolque(s) o semirremolque(s) que se adaptan al autotransporte para realizar el traslado de los bienes y/o mercancías.</para>
        /// </summary>
        [DescriptionAttribute("Nodo condicional para registrar los datos del(los) remolque(s) o semirremolque(s)" +
            " que se adaptan al autotransporte para realizar el traslado de los bienes y/o me" +
            "rcancías.")]
        [XmlArrayAttribute("Remolques")]
        [XmlArrayItemAttribute("Remolque", Namespace="http://www.sat.gob.mx/CartaPorte30")]
        public Collection<CartaPorteMercanciasAutotransporteRemolquesRemolque> Remolques
        {
            get
            {
                return _remolques;
            }
            private set
            {
                _remolques = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Remolques collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool RemolquesSpecified
        {
            get
            {
                return (this.Remolques.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CartaPorteMercanciasAutotransporte" /> class.</para>
        /// </summary>
        public CartaPorteMercanciasAutotransporte()
        {
            this._remolques = new Collection<CartaPorteMercanciasAutotransporteRemolquesRemolque>();
        }
        
        /// <summary>
        /// <para>Atributo requerido para registrar la clave del tipo de permiso proporcionado por la Secretaría de Infraestructura, Comunicaciones y Transportes (SICT) o la autoridad análoga, el cual debe corresponder con el tipo de autotransporte utilizado para el traslado de los bienes y/o mercancías de acuerdo al catálogo correspondiente.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo requerido para registrar la clave del tipo de permiso proporcionado por la Secretaría de Infraestructura, Comunicaciones y Transportes (SICT) o la autoridad análoga, el cual debe corresponder con el tipo de autotransporte utilizado para el traslado de los bienes y/o mercancías de acuerdo al catálogo correspondiente.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("PermSCT")]
        public string PermSct { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar el número del permiso otorgado por la Secretaría de Infraestructura, Comunicaciones y Transportes (SICT) o la autoridad correspondiente, al autotransporte utilizado para el traslado de los bienes y/o mercancías.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,50}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar el número del permiso otorgado por la Secretarí" +
            "a de Infraestructura, Comunicaciones y Transportes (SICT) o la autoridad corresp" +
            "ondiente, al autotransporte utilizado para el traslado de los bienes y/o mercanc" +
            "ías.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(50)]
        [RegularExpressionAttribute("[^|]{1,50}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("NumPermisoSCT")]
        public string NumPermisoSct { get; set; }
    }
}
