//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v30
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteMercanciasMercancia", Namespace="http://www.sat.gob.mx/CartaPorte30", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("CartaPorteMercanciasMercancia", Namespace="http://www.sat.gob.mx/CartaPorte30")]
    public partial class CartaPorteMercanciasMercancia
    {
        
        [XmlIgnoreAttribute()]
        private Collection<CartaPorteMercanciasMercanciaDocumentacionAduanera> _documentacionAduanera;
        
        /// <summary>
        /// <para>Nodo condicional para registrar la información del(los) documento(s) aduanero(s) que se encuentra(n) asociado(s) al traslado de los bienes y/o mercancías por los distintos medios de transporte de procedencia extranjera para acreditar la legal estancia o tenencia durante su traslado en territorio nacional.</para>
        /// </summary>
        [DescriptionAttribute(@"Nodo condicional para registrar la información del(los) documento(s) aduanero(s) que se encuentra(n) asociado(s) al traslado de los bienes y/o mercancías por los distintos medios de transporte de procedencia extranjera para acreditar la legal estancia o tenencia durante su traslado en territorio nacional.")]
        [XmlElementAttribute("DocumentacionAduanera")]
        public Collection<CartaPorteMercanciasMercanciaDocumentacionAduanera> DocumentacionAduanera
        {
            get
            {
                return _documentacionAduanera;
            }
            private set
            {
                _documentacionAduanera = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the DocumentacionAduanera collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool DocumentacionAduaneraSpecified
        {
            get
            {
                return (this.DocumentacionAduanera.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CartaPorteMercanciasMercancia" /> class.</para>
        /// </summary>
        public CartaPorteMercanciasMercancia()
        {
            this._documentacionAduanera = new Collection<CartaPorteMercanciasMercanciaDocumentacionAduanera>();
            this._guiasIdentificacion = new Collection<CartaPorteMercanciasMercanciaGuiasIdentificacion>();
            this._cantidadTransporta = new Collection<CartaPorteMercanciasMercanciaCantidadTransporta>();
        }
        
        [XmlIgnoreAttribute()]
        private Collection<CartaPorteMercanciasMercanciaGuiasIdentificacion> _guiasIdentificacion;
        
        /// <summary>
        /// <para>Nodo condicional para registrar la información del(los) número(s) de guía(s) que se encuentre(n) asociado(s) al(los) paquete(s) que se traslada(n) dentro del territorio nacional.</para>
        /// </summary>
        [DescriptionAttribute("Nodo condicional para registrar la información del(los) número(s) de guía(s) que " +
            "se encuentre(n) asociado(s) al(los) paquete(s) que se traslada(n) dentro del ter" +
            "ritorio nacional.")]
        [XmlElementAttribute("GuiasIdentificacion")]
        public Collection<CartaPorteMercanciasMercanciaGuiasIdentificacion> GuiasIdentificacion
        {
            get
            {
                return _guiasIdentificacion;
            }
            private set
            {
                _guiasIdentificacion = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the GuiasIdentificacion collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool GuiasIdentificacionSpecified
        {
            get
            {
                return (this.GuiasIdentificacion.Count != 0);
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<CartaPorteMercanciasMercanciaCantidadTransporta> _cantidadTransporta;
        
        /// <summary>
        /// <para>Nodo opcional para registrar la cantidad de los bienes y/o mercancías que se trasladan a través de los distintos medios de transporte, que será captada o distribuida en distintos puntos, a fin de identificar el punto de origen y destino correspondiente.</para>
        /// </summary>
        [DescriptionAttribute("Nodo opcional para registrar la cantidad de los bienes y/o mercancías que se tras" +
            "ladan a través de los distintos medios de transporte, que será captada o distrib" +
            "uida en distintos puntos, a fin de identificar el punto de origen y destino corr" +
            "espondiente.")]
        [XmlElementAttribute("CantidadTransporta")]
        public Collection<CartaPorteMercanciasMercanciaCantidadTransporta> CantidadTransporta
        {
            get
            {
                return _cantidadTransporta;
            }
            private set
            {
                _cantidadTransporta = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the CantidadTransporta collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool CantidadTransportaSpecified
        {
            get
            {
                return (this.CantidadTransporta.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>Nodo condicional para registrar especificaciones de los bienes y/o mercancías que se trasladan a través de los distintos medios de transporte.</para>
        /// </summary>
        [DescriptionAttribute("Nodo condicional para registrar especificaciones de los bienes y/o mercancías que" +
            " se trasladan a través de los distintos medios de transporte.")]
        [XmlElementAttribute("DetalleMercancia")]
        public CartaPorteMercanciasMercanciaDetalleMercancia DetalleMercancia { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar la clave de producto de los bienes y/o mercancías que se trasladan en los distintos medios de transporte.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar la clave de producto de los bienes y/o mercancí" +
            "as que se trasladan en los distintos medios de transporte.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("BienesTransp")]
        public string BienesTransp { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para expresar la clave de producto de la STCC (por sus siglas en inglés, Standard Transportation Commodity Code), cuando el medio de transporte utilizado para el traslado de los bienes y/o mercancías sea ferroviario.</para>
        /// <para xml:lang="en">Minimum length: 6.</para>
        /// <para xml:lang="en">Maximum length: 7.</para>
        /// <para xml:lang="en">Pattern: [0-9|]{6,7}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para expresar la clave de producto de la STCC (por sus siglas e" +
            "n inglés, Standard Transportation Commodity Code), cuando el medio de transporte" +
            " utilizado para el traslado de los bienes y/o mercancías sea ferroviario.")]
        [MinLengthAttribute(6)]
        [MaxLengthAttribute(7)]
        [RegularExpressionAttribute("[0-9|]{6,7}")]
        [XmlAttributeAttribute("ClaveSTCC")]
        public string ClaveStcc { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para detallar las características de los bienes y/o mercancías que se trasladan en los distintos medios de transporte.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1000.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,1000}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para detallar las características de los bienes y/o mercancías" +
            " que se trasladan en los distintos medios de transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(1000)]
        [RegularExpressionAttribute("[^|]{1,1000}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Descripcion")]
        public string Descripcion { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar la cantidad total de los bienes y/o mercancías que se trasladan a través de los distintos medios de transporte.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.000001.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar la cantidad total de los bienes y/o mercancías q" +
            "ue se trasladan a través de los distintos medios de transporte.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Cantidad")]
        public decimal Cantidad { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar la clave de la unidad de medida estandarizada aplicable para la cantidad de los bienes y/o mercancías que se trasladan en los distintos medios de transporte. La unidad debe corresponder con la descripción de los bienes y/o mercancías registrados.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo requerido para registrar la clave de la unidad de medida estandarizada aplicable para la cantidad de los bienes y/o mercancías que se trasladan en los distintos medios de transporte. La unidad debe corresponder con la descripción de los bienes y/o mercancías registrados.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("ClaveUnidad")]
        public string ClaveUnidad { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar la unidad de medida propia para la cantidad de los bienes y/o mercancías que se trasladan a través de los distintos medios de transporte. La unidad debe corresponder con la descripción de los bienes y/o mercancías.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,20}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para registrar la unidad de medida propia para la cantidad de l" +
            "os bienes y/o mercancías que se trasladan a través de los distintos medios de tr" +
            "ansporte. La unidad debe corresponder con la descripción de los bienes y/o merca" +
            "ncías.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(20)]
        [RegularExpressionAttribute("[^|]{1,20}")]
        [XmlAttributeAttribute("Unidad")]
        public string Unidad { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para expresar las medidas del empaque de los bienes y/o mercancías que se trasladan en los distintos medios de transporte. Se debe registrar la longitud, la altura y la anchura en centímetros o en pulgadas, separados dichos valores con una diagonal, i.e. 30/40/30cm.</para>
        /// <para xml:lang="en">Pattern: ([0-9]{1,3}[/]){2}([0-9]{1,3})(cm|plg).</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo opcional para expresar las medidas del empaque de los bienes y/o mercancías que se trasladan en los distintos medios de transporte. Se debe registrar la longitud, la altura y la anchura en centímetros o en pulgadas, separados dichos valores con una diagonal, i.e. 30/40/30cm.")]
        [RegularExpressionAttribute("([0-9]{1,3}[/]){2}([0-9]{1,3})(cm|plg)")]
        [XmlAttributeAttribute("Dimensiones")]
        public string Dimensiones { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para precisar que los bienes y/o mercancías que se trasladan son considerados o clasificados como material peligroso.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para precisar que los bienes y/o mercancías que se trasladan" +
            " son considerados o clasificados como material peligroso.")]
        [XmlAttributeAttribute("MaterialPeligroso")]
        public string MaterialPeligroso { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para indicar la clave del tipo de material peligroso que se transporta de acuerdo a la NOM-002-SCT/2011.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para indicar la clave del tipo de material peligroso que se " +
            "transporta de acuerdo a la NOM-002-SCT/2011.")]
        [XmlAttributeAttribute("CveMaterialPeligroso")]
        public string CveMaterialPeligroso { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para precisar la clave del tipo de embalaje que se requiere para transportar el material o residuo peligroso.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para precisar la clave del tipo de embalaje que se requiere " +
            "para transportar el material o residuo peligroso.")]
        [XmlAttributeAttribute("Embalaje")]
        public string Embalaje { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para expresar la descripción del embalaje de los bienes y/o mercancías que se trasladan y que se consideran material o residuo peligroso.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,100}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para expresar la descripción del embalaje de los bienes y/o mer" +
            "cancías que se trasladan y que se consideran material o residuo peligroso.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(100)]
        [RegularExpressionAttribute("[^|]{1,100}")]
        [XmlAttributeAttribute("DescripEmbalaje")]
        public string DescripEmbalaje { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para expresar la clasificación del producto que se traslada a través de los distintos medios de transporte y que debe contar con autorización por la autoridad correspondiente.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para expresar la clasificación del producto que se traslada a t" +
            "ravés de los distintos medios de transporte y que debe contar con autorización p" +
            "or la autoridad correspondiente.")]
        [XmlAttributeAttribute("SectorCOFEPRIS")]
        public string SectorCofepris { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el nombre común del ingrediente activo de los precursores, químicos de uso dual, plaguicidas o fertilizantes que se trasladan a través de los distintos medios de transporte.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1000.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,1000}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar el nombre común del ingrediente activo de los " +
            "precursores, químicos de uso dual, plaguicidas o fertilizantes que se trasladan " +
            "a través de los distintos medios de transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(1000)]
        [RegularExpressionAttribute("[^|]{1,1000}")]
        [XmlAttributeAttribute("NombreIngredienteActivo")]
        public string NombreIngredienteActivo { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el nombre de la sustancia activa de los precursores, químicos de uso dual o sustancias tóxicas que se traslada a través de los distintos medios de transporte.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 150.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,150}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar el nombre de la sustancia activa de los precur" +
            "sores, químicos de uso dual o sustancias tóxicas que se traslada a través de los" +
            " distintos medios de transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(150)]
        [RegularExpressionAttribute("[^|]{1,150}")]
        [XmlAttributeAttribute("NomQuimico")]
        public string NomQuimico { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el fármaco o la sustancia activa del medicamento, psicotrópico o estupefaciente que se traslada a través de los distintos medios de transporte.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,50}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar el fármaco o la sustancia activa del medicamen" +
            "to, psicotrópico o estupefaciente que se traslada a través de los distintos medi" +
            "os de transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(50)]
        [RegularExpressionAttribute("[^|]{1,50}")]
        [XmlAttributeAttribute("DenominacionGenericaProd")]
        public string DenominacionGenericaProd { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar la marca con la que se comercializa el producto o nombre que le asigna el laboratorio o fabricante a sus especialidades farmacéuticas con el fin de distinguirlas de otras similares del medicamento, psicotrópico o estupefaciente que se traslada a través de los distintos medios de transporte.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,50}.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para expresar la marca con la que se comercializa el producto o nombre que le asigna el laboratorio o fabricante a sus especialidades farmacéuticas con el fin de distinguirlas de otras similares del medicamento, psicotrópico o estupefaciente que se traslada a través de los distintos medios de transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(50)]
        [RegularExpressionAttribute("[^|]{1,50}")]
        [XmlAttributeAttribute("DenominacionDistintivaProd")]
        public string DenominacionDistintivaProd { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el nombre o razón social del establecimiento que realiza la fabricación o manufactura del medicamento, precursor, químico de uso dual, psicotrópico o estupefaciente que se traslada a través de los distintos medios de transporte.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 240.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,240}.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para expresar el nombre o razón social del establecimiento que realiza la fabricación o manufactura del medicamento, precursor, químico de uso dual, psicotrópico o estupefaciente que se traslada a través de los distintos medios de transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(240)]
        [RegularExpressionAttribute("[^|]{1,240}")]
        [XmlAttributeAttribute("Fabricante")]
        public string Fabricante { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar la fecha de caducidad del medicamento, psicotrópico o estupefaciente; o para expresar la fecha de reanálisis del precursor o químico de uso dual que se traslada a través de los distintos medios de transporte. 
        ///Se expresa en la forma AAAA-MM-DD.</para>
        /// <para>Tipo definido para la expresión de la fecha. Se expresa en la forma AAAA-MM-DD.</para>
        /// <para xml:lang="en">Pattern: ((19|20)[0-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]).</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para registrar la fecha de caducidad del medicamento, psicotrópico o estupefaciente; o para expresar la fecha de reanálisis del precursor o químico de uso dual que se traslada a través de los distintos medios de transporte. Se expresa en la forma AAAA-MM-DD.")]
        [RegularExpressionAttribute("((19|20)[0-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("FechaCaducidad", DataType="date")]
        public DateTime FechaCaducidadValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the FechaCaducidad property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool FechaCaducidadValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar la fecha de caducidad del medicamento, psicotrópico o estupefaciente; o para expresar la fecha de reanálisis del precursor o químico de uso dual que se traslada a través de los distintos medios de transporte. 
        ///Se expresa en la forma AAAA-MM-DD.</para>
        /// <para>Tipo definido para la expresión de la fecha. Se expresa en la forma AAAA-MM-DD.</para>
        /// <para xml:lang="en">Pattern: ((19|20)[0-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]).</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<DateTime> FechaCaducidad
        {
            get
            {
                if (this.FechaCaducidadValueSpecified)
                {
                    return this.FechaCaducidadValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.FechaCaducidadValue = value.GetValueOrDefault();
                this.FechaCaducidadValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Atributo condicional para expresar la denominación que identifica y confiere trazabilidad del medicamento, precursor, químico de uso dual, psicotrópico o estupefaciente elaborado en un ciclo de producción, bajo condiciones equivalentes de operación y durante un periodo.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 10.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,10}.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para expresar la denominación que identifica y confiere trazabilidad del medicamento, precursor, químico de uso dual, psicotrópico o estupefaciente elaborado en un ciclo de producción, bajo condiciones equivalentes de operación y durante un periodo.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(10)]
        [RegularExpressionAttribute("[^|]{1,10}")]
        [XmlAttributeAttribute("LoteMedicamento")]
        public string LoteMedicamento { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar la forma farmacéutica o mezcla del medicamento, precursor, químico de uso dual, psicotrópico o estupefaciente que presenta ciertas características físicas para su adecuada dosificación, conservación y administración.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar la forma farmacéutica o mezcla del medicamento" +
            ", precursor, químico de uso dual, psicotrópico o estupefaciente que presenta cie" +
            "rtas características físicas para su adecuada dosificación, conservación y admin" +
            "istración.")]
        [XmlAttributeAttribute("FormaFarmaceutica")]
        public string FormaFarmaceutica { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar la condición en la cual es necesario mantener el medicamento, precursor, químico de uso dual, psicotrópicos o estupefacientes durante el traslado y almacenamiento.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar la condición en la cual es necesario mantener " +
            "el medicamento, precursor, químico de uso dual, psicotrópicos o estupefacientes " +
            "durante el traslado y almacenamiento.")]
        [XmlAttributeAttribute("CondicionesEspTransp")]
        public string CondicionesEspTransp { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el registro sanitario o folio de autorización con el que cuenta la empresa para el traslado del medicamento, psicotrópico o estupefaciente.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,15}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar el registro sanitario o folio de autorización " +
            "con el que cuenta la empresa para el traslado del medicamento, psicotrópico o es" +
            "tupefaciente.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(15)]
        [RegularExpressionAttribute("[^|]{1,15}")]
        [XmlAttributeAttribute("RegistroSanitarioFolioAutorizacion")]
        public string RegistroSanitarioFolioAutorizacion { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar el folio del permiso de importación con el que cuenta el medicamento, precursor, químico de uso dual, psicotrópico o estupefaciente.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 6.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,6}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar el folio del permiso de importación con el qu" +
            "e cuenta el medicamento, precursor, químico de uso dual, psicotrópico o estupefa" +
            "ciente.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(6)]
        [RegularExpressionAttribute("[^|]{1,6}")]
        [XmlAttributeAttribute("PermisoImportacion")]
        public string PermisoImportacion { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar el número de folio de importación VUCEM para la identificación del documento, para el traslado de medicamentos, precursores o químicos de uso dual, sustancias tóxicas, plaguicidas o fertizantes.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 25.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,25}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar el número de folio de importación VUCEM para " +
            "la identificación del documento, para el traslado de medicamentos, precursores o" +
            " químicos de uso dual, sustancias tóxicas, plaguicidas o fertizantes.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(25)]
        [RegularExpressionAttribute("[^|]{1,25}")]
        [XmlAttributeAttribute("FolioImpoVUCEM")]
        public string FolioImpoVucem { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el número Chemical Abstracts Service (CAS) con el que se identifica el compuesto químico de la sustancia tóxica.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,15}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar el número Chemical Abstracts Service (CAS) con" +
            " el que se identifica el compuesto químico de la sustancia tóxica.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(15)]
        [RegularExpressionAttribute("[^|]{1,15}")]
        [XmlAttributeAttribute("NumCAS")]
        public string NumCas { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el nombre o razón social de la empresa importadora de las sustancias tóxicas.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 80.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,80}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar el nombre o razón social de la empresa importa" +
            "dora de las sustancias tóxicas.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(80)]
        [RegularExpressionAttribute("[^|]{1,80}")]
        [XmlAttributeAttribute("RazonSocialEmpImp")]
        public string RazonSocialEmpImp { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el número de registro sanitario para plaguicidas o fertilizantes cuya importación, comercialización y uso están permitidos en México, mismo que emite la Comisión Intersecretarial para el Control del Proceso y Uso de Plaguicidas, Fertilizantes y Sustancias Tóxicas (CICLOPLAFEST).</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 60.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,60}.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para expresar el número de registro sanitario para plaguicidas o fertilizantes cuya importación, comercialización y uso están permitidos en México, mismo que emite la Comisión Intersecretarial para el Control del Proceso y Uso de Plaguicidas, Fertilizantes y Sustancias Tóxicas (CICLOPLAFEST).")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(60)]
        [RegularExpressionAttribute("[^|]{1,60}")]
        [XmlAttributeAttribute("NumRegSanPlagCOFEPRIS")]
        public string NumRegSanPlagCofepris { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar el país y nombre o razón social de quien produce o fabrica el ingrediente activo del plaguicida o fertilizante.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 600.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,600}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar el país y nombre o razón social de quien prod" +
            "uce o fabrica el ingrediente activo del plaguicida o fertilizante.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(600)]
        [RegularExpressionAttribute("[^|]{1,600}")]
        [XmlAttributeAttribute("DatosFabricante")]
        public string DatosFabricante { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar el país y nombre o razón social de quien formula el ingrediente activo del plaguicida o fertilizante.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 600.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,600}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar el país y nombre o razón social de quien form" +
            "ula el ingrediente activo del plaguicida o fertilizante.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(600)]
        [RegularExpressionAttribute("[^|]{1,600}")]
        [XmlAttributeAttribute("DatosFormulador")]
        public string DatosFormulador { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar el país y nombre o razón social de quien maquila el ingrediente activo del plaguicida o fertilizante.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 600.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,600}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar el país y nombre o razón social de quien maqu" +
            "ila el ingrediente activo del plaguicida o fertilizante.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(600)]
        [RegularExpressionAttribute("[^|]{1,600}")]
        [XmlAttributeAttribute("DatosMaquilador")]
        public string DatosMaquilador { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar el uso autorizado del plaguicida o fertilizante de acuerdo a la regulación del país.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1000.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,1000}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar el uso autorizado del plaguicida o fertilizan" +
            "te de acuerdo a la regulación del país.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(1000)]
        [RegularExpressionAttribute("[^|]{1,1000}")]
        [XmlAttributeAttribute("UsoAutorizado")]
        public string UsoAutorizado { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para indicar en kilogramos el peso estimado de los bienes y/o mercancías que se trasladan en los distintos medios de transporte.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.001.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 3.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para indicar en kilogramos el peso estimado de los bienes y/o " +
            "mercancías que se trasladan en los distintos medios de transporte.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("PesoEnKg")]
        public decimal PesoEnKg { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el monto del valor de los bienes y/o mercancías que se trasladan en los distintos medios de transporte, de acuerdo al valor mercado, al valor pactado en la contraprestación o bien al valor estimado que determine el contribuyente.</para>
        /// <para>Tipo definido para expresar importes numéricos con fracción hasta seis decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.000000.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,6})?.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para expresar el monto del valor de los bienes y/o mercancías que se trasladan en los distintos medios de transporte, de acuerdo al valor mercado, al valor pactado en la contraprestación o bien al valor estimado que determine el contribuyente.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,6})?")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("ValorMercancia")]
        public decimal ValorMercanciaValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ValorMercancia property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool ValorMercanciaValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el monto del valor de los bienes y/o mercancías que se trasladan en los distintos medios de transporte, de acuerdo al valor mercado, al valor pactado en la contraprestación o bien al valor estimado que determine el contribuyente.</para>
        /// <para>Tipo definido para expresar importes numéricos con fracción hasta seis decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.000000.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,6})?.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<decimal> ValorMercancia
        {
            get
            {
                if (this.ValorMercanciaValueSpecified)
                {
                    return this.ValorMercanciaValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ValorMercanciaValue = value.GetValueOrDefault();
                this.ValorMercanciaValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Atributo condicional para identificar la clave de la moneda utilizada para expresar el valor de los bienes y/o mercancías que se trasladan en los distintos medios de transporte. Cuando se usa moneda nacional se registra MXN, de acuerdo a la especificación ISO 4217.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para identificar la clave de la moneda utilizada para expresar el valor de los bienes y/o mercancías que se trasladan en los distintos medios de transporte. Cuando se usa moneda nacional se registra MXN, de acuerdo a la especificación ISO 4217.")]
        [XmlAttributeAttribute("Moneda")]
        public string Moneda { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional que sirve para expresar la clave de la fracción arancelaria que corresponde con la descripción de los bienes y/o mercancías que se trasladan en los distintos medios de transporte.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional que sirve para expresar la clave de la fracción arancelaria " +
            "que corresponde con la descripción de los bienes y/o mercancías que se trasladan" +
            " en los distintos medios de transporte.")]
        [XmlAttributeAttribute("FraccionArancelaria")]
        public string FraccionArancelaria { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para expresar el folio fiscal (UUID) del comprobante de comercio exterior que se relaciona.</para>
        /// <para xml:lang="en">Pattern: [a-f0-9A-F]{8}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{12}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para expresar el folio fiscal (UUID) del comprobante de comerci" +
            "o exterior que se relaciona.")]
        [RegularExpressionAttribute("[a-f0-9A-F]{8}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{12}")]
        [XmlAttributeAttribute("UUIDComercioExt")]
        public string UuidComercioExt { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el estado de la materia o producto al realizar una operación de comercio exterior a través de los distintos medios de transporte.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar el estado de la materia o producto al realizar" +
            " una operación de comercio exterior a través de los distintos medios de transpor" +
            "te.")]
        [XmlAttributeAttribute("TipoMateria")]
        public string TipoMateria { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar la descripción del estado de la materia o producto al realizar una operación de comercio exterior a través de los distintos medios de transporte.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,50}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar la descripción del estado de la materia o prod" +
            "ucto al realizar una operación de comercio exterior a través de los distintos me" +
            "dios de transporte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(50)]
        [RegularExpressionAttribute("[^|]{1,50}")]
        [XmlAttributeAttribute("DescripcionMateria")]
        public string DescripcionMateria { get; set; }
    }
}
