//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v30
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteMercanciasTransporteMaritimoContenedor", Namespace="http://www.sat.gob.mx/CartaPorte30", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("CartaPorteMercanciasTransporteMaritimoContenedor", Namespace="http://www.sat.gob.mx/CartaPorte30")]
    public partial class CartaPorteMercanciasTransporteMaritimoContenedor
    {
        
        /// <summary>
        /// <para>Atributo requerido para registrar la clave de identificación correspondiente con el tipo de contenedor marítimo en el que se transportan los bienes y/o mercancías.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar la clave de identificación correspondiente con " +
            "el tipo de contenedor marítimo en el que se transportan los bienes y/o mercancía" +
            "s.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TipoContenedor")]
        public string TipoContenedor { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar la matrícula o el número de identificación del contenedor marítimo en el que se transportan los bienes y/o mercancías, el cual está integrado por el código del propietario, el número de serie y el dígito de control correspondiente.</para>
        /// <para xml:lang="en">Minimum length: 11.</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// <para xml:lang="en">Pattern: [^|]{11,15}.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para registrar la matrícula o el número de identificación del contenedor marítimo en el que se transportan los bienes y/o mercancías, el cual está integrado por el código del propietario, el número de serie y el dígito de control correspondiente.")]
        [MinLengthAttribute(11)]
        [MaxLengthAttribute(15)]
        [RegularExpressionAttribute("[^|]{11,15}")]
        [XmlAttributeAttribute("MatriculaContenedor")]
        public string MatriculaContenedor { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar el número del sello o precinto de los contenedores marítimos que son utilizados para trasladar los bienes y/o mercancías.</para>
        /// <para xml:lang="en">Minimum length: 5.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// <para xml:lang="en">Pattern: [^|]{5,20}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar el número del sello o precinto de los contene" +
            "dores marítimos que son utilizados para trasladar los bienes y/o mercancías.")]
        [MinLengthAttribute(5)]
        [MaxLengthAttribute(20)]
        [RegularExpressionAttribute("[^|]{5,20}")]
        [XmlAttributeAttribute("NumPrecinto")]
        public string NumPrecinto { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar el identificador del complemento Carta Porte (IdCCP) de un CFDI previamente certificado para el traslado de bienes o mercancías mediante autotransporte, únicamente aplica para traslados mediante ferri.</para>
        /// <para xml:lang="en">Minimum length: 36.</para>
        /// <para xml:lang="en">Maximum length: 36.</para>
        /// <para xml:lang="en">Pattern: [C]{3}[a-f0-9A-F]{5}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{12}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar el identificador del complemento Carta Porte " +
            "(IdCCP) de un CFDI previamente certificado para el traslado de bienes o mercancí" +
            "as mediante autotransporte, únicamente aplica para traslados mediante ferri.")]
        [MinLengthAttribute(36)]
        [MaxLengthAttribute(36)]
        [RegularExpressionAttribute("[C]{3}[a-f0-9A-F]{5}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{12}" +
            "")]
        [XmlAttributeAttribute("IdCCPRelacionado")]
        public string IdCcpRelacionado { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar los caracteres alfanuméricos, sin guiones ni espacios de la placa vehicular del autotransporte registrado en el CFDI con complemento Carta Porte del autotransporte, únicamente aplica para traslado mediante ferri.</para>
        /// <para xml:lang="en">Pattern: [^(?!.*\s)-]{5,7}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar los caracteres alfanuméricos, sin guiones ni " +
            "espacios de la placa vehicular del autotransporte registrado en el CFDI con comp" +
            "lemento Carta Porte del autotransporte, únicamente aplica para traslado mediante" +
            " ferri.")]
        [RegularExpressionAttribute("[^(?!.*\\s)-]{5,7}")]
        [XmlAttributeAttribute("PlacaVMCCP")]
        public string PlacaVmccp { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar la fecha y hora de certificación del CDFI con complemento Carta Porte del autotransporte, únicamente aplica para traslado mediante ferri.</para>
        /// <para>Tipo definido para la expresión de la fecha y hora. Se expresa en la forma AAAA-MM-DDThh:mm:ss</para>
        /// <para xml:lang="en">Pattern: (20[1-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]).</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar la fecha y hora de certificación del CDFI con" +
            " complemento Carta Porte del autotransporte, únicamente aplica para traslado med" +
            "iante ferri.")]
        [RegularExpressionAttribute("(20[1-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5]" +
            "[0-9]:[0-5][0-9])")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("FechaCertificacionCCP", DataType="dateTime")]
        public DateTime FechaCertificacionCcpValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the FechaCertificacionCcp property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool FechaCertificacionCcpValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar la fecha y hora de certificación del CDFI con complemento Carta Porte del autotransporte, únicamente aplica para traslado mediante ferri.</para>
        /// <para>Tipo definido para la expresión de la fecha y hora. Se expresa en la forma AAAA-MM-DDThh:mm:ss</para>
        /// <para xml:lang="en">Pattern: (20[1-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]).</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<DateTime> FechaCertificacionCcp
        {
            get
            {
                if (this.FechaCertificacionCcpValueSpecified)
                {
                    return this.FechaCertificacionCcpValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.FechaCertificacionCcpValue = value.GetValueOrDefault();
                this.FechaCertificacionCcpValueSpecified = value.HasValue;
            }
        }
    }
}
