//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v30
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteMercanciasAutotransporteIdentificacionVehicular", Namespace="http://www.sat.gob.mx/CartaPorte30", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("CartaPorteMercanciasAutotransporteIdentificacionVehicular", Namespace="http://www.sat.gob.mx/CartaPorte30")]
    public partial class CartaPorteMercanciasAutotransporteIdentificacionVehicular
    {
        
        /// <summary>
        /// <para>Atributo requerido para expresar la clave de nomenclatura del autotransporte que es utilizado para transportar los bienes y/o mercancías.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar la clave de nomenclatura del autotransporte que " +
            "es utilizado para transportar los bienes y/o mercancías.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("ConfigVehicular")]
        public string ConfigVehicular { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para indicar en toneladas el peso bruto vehicular permitido del autotransporte de acuerdo a la NOM-SCT-012-2017 que es utilizado para realizar el traslado de los bienes y/o mercancías.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.01.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para indicar en toneladas el peso bruto vehicular permitido de" +
            "l autotransporte de acuerdo a la NOM-SCT-012-2017 que es utilizado para realizar" +
            " el traslado de los bienes y/o mercancías.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("PesoBrutoVehicular")]
        public decimal PesoBrutoVehicular { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar solo los caracteres alfanuméricos, sin guiones ni espacios de la placa vehicular del autotransporte que es utilizado para transportar los bienes y/o mercancías.</para>
        /// <para xml:lang="en">Pattern: [^(?!.*\s)-]{5,7}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar solo los caracteres alfanuméricos, sin guiones " +
            "ni espacios de la placa vehicular del autotransporte que es utilizado para trans" +
            "portar los bienes y/o mercancías.")]
        [RegularExpressionAttribute("[^(?!.*\\s)-]{5,7}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("PlacaVM")]
        public string PlacaVm { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar el año del autotransporte que es utilizado para transportar los bienes y/o mercancías.</para>
        /// <para xml:lang="en">Pattern: (19[0-9]{2}|20[0-9]{2}).</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar el año del autotransporte que es utilizado para" +
            " transportar los bienes y/o mercancías.")]
        [RegularExpressionAttribute("(19[0-9]{2}|20[0-9]{2})")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("AnioModeloVM")]
        public int AnioModeloVm { get; set; }
    }
}
