//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v30
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteMercanciasAutotransporteRemolques", Namespace="http://www.sat.gob.mx/CartaPorte30", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("CartaPorteMercanciasAutotransporteRemolques", Namespace="http://www.sat.gob.mx/CartaPorte30")]
    public partial class CartaPorteMercanciasAutotransporteRemolques
    {
        
        [XmlIgnoreAttribute()]
        private Collection<CartaPorteMercanciasAutotransporteRemolquesRemolque> _remolque;
        
        /// <summary>
        /// <para>Nodo requerido para expresar la información del(los) remolque(s) o semirremolque(s) que se adapta(n) al autotransporte para realizar el traslado de los bienes y/o mercancías.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para expresar la información del(los) remolque(s) o semirremolque(" +
            "s) que se adapta(n) al autotransporte para realizar el traslado de los bienes y/" +
            "o mercancías.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Remolque")]
        public Collection<CartaPorteMercanciasAutotransporteRemolquesRemolque> Remolque
        {
            get
            {
                return _remolque;
            }
            private set
            {
                _remolque = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CartaPorteMercanciasAutotransporteRemolques" /> class.</para>
        /// </summary>
        public CartaPorteMercanciasAutotransporteRemolques()
        {
            this._remolque = new Collection<CartaPorteMercanciasAutotransporteRemolquesRemolque>();
        }
    }
}
