//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v30
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteMercanciasTransporteAereo", Namespace="http://www.sat.gob.mx/CartaPorte30", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("CartaPorteMercanciasTransporteAereo", Namespace="http://www.sat.gob.mx/CartaPorte30")]
    public partial class CartaPorteMercanciasTransporteAereo
    {
        
        /// <summary>
        /// <para>Atributo requerido para registrar la clave del permiso proporcionado por la Secretaría de Infraestructura, Comunicaciones y Transportes (SICT), o la autoridad análoga, la cual debe corresponder con la aeronave que se está utilizando para realizar el traslado de los bienes y/o mercancías por vía aérea.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo requerido para registrar la clave del permiso proporcionado por la Secretaría de Infraestructura, Comunicaciones y Transportes (SICT), o la autoridad análoga, la cual debe corresponder con la aeronave que se está utilizando para realizar el traslado de los bienes y/o mercancías por vía aérea.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("PermSCT")]
        public string PermSct { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar el número de permiso o valor análogo proporcionado por la Secretaría de Infraestructura, Comunicaciones y Transportes (SICT), o la autoridad análoga, según corresponda, para el transporte de bienes y/o mercancías por vía aérea.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,50}.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo requerido para registrar el número de permiso o valor análogo proporcionado por la Secretaría de Infraestructura, Comunicaciones y Transportes (SICT), o la autoridad análoga, según corresponda, para el transporte de bienes y/o mercancías por vía aérea.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(50)]
        [RegularExpressionAttribute("[^|]{1,50}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("NumPermisoSCT")]
        public string NumPermisoSct { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar el número de la matrícula de la aeronave con la que se realiza el traslado de los bienes y/o mercancías en territorio nacional el cual tiene una longitud de 10 posiciones y se compone de valores alfanuméricos, más el carácter especial denominado guion medio “-“.</para>
        /// <para xml:lang="en">Minimum length: 5.</para>
        /// <para xml:lang="en">Maximum length: 11.</para>
        /// <para xml:lang="en">Pattern: ([A-Z]|[0-9]|-){5,11}.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo opcional para registrar el número de la matrícula de la aeronave con la que se realiza el traslado de los bienes y/o mercancías en territorio nacional el cual tiene una longitud de 10 posiciones y se compone de valores alfanuméricos, más el carácter especial denominado guion medio “-“.")]
        [MinLengthAttribute(5)]
        [MaxLengthAttribute(11)]
        [RegularExpressionAttribute("([A-Z]|[0-9]|-){5,11}")]
        [XmlAttributeAttribute("MatriculaAeronave")]
        public string MatriculaAeronave { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar el nombre de la aseguradora que cubre los riesgos de la aeronave con la que transportan los bienes y/o mercancías.</para>
        /// <para xml:lang="en">Minimum length: 3.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [^|]{3,50}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para registrar el nombre de la aseguradora que cubre los riesgo" +
            "s de la aeronave con la que transportan los bienes y/o mercancías.")]
        [MinLengthAttribute(3)]
        [MaxLengthAttribute(50)]
        [RegularExpressionAttribute("[^|]{3,50}")]
        [XmlAttributeAttribute("NombreAseg")]
        public string NombreAseg { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar el número de póliza asignado por la aseguradora que cubre la protección e indemnización por responsabilidad civil de la aeronave que transporta los bienes y/o mercancías.</para>
        /// <para xml:lang="en">Minimum length: 3.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// <para xml:lang="en">Pattern: [^|]{3,30}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para registrar el número de póliza asignado por la aseguradora " +
            "que cubre la protección e indemnización por responsabilidad civil de la aeronave" +
            " que transporta los bienes y/o mercancías.")]
        [MinLengthAttribute(3)]
        [MaxLengthAttribute(30)]
        [RegularExpressionAttribute("[^|]{3,30}")]
        [XmlAttributeAttribute("NumPolizaSeguro")]
        public string NumPolizaSeguro { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar el número de guía aérea con el que se trasladan los bienes y/o mercancías.</para>
        /// <para xml:lang="en">Minimum length: 12.</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// <para xml:lang="en">Pattern: [^|]{12,15}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar el número de guía aérea con el que se trasladan" +
            " los bienes y/o mercancías.")]
        [MinLengthAttribute(12)]
        [MaxLengthAttribute(15)]
        [RegularExpressionAttribute("[^|]{12,15}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("NumeroGuia")]
        public string NumeroGuia { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar el lugar, entidad, región, localidad o análogo, donde se celebró el contrato para realizar el traslado de los bienes y/o mercancías.</para>
        /// <para>Tipo definido para expresar la colonia, localidad o municipio en que está ubicado el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 120.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,120}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para registrar el lugar, entidad, región, localidad o análogo, " +
            "donde se celebró el contrato para realizar el traslado de los bienes y/o mercanc" +
            "ías.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(120)]
        [RegularExpressionAttribute("[^|]{1,120}")]
        [XmlAttributeAttribute("LugarContrato")]
        public string LugarContrato { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar el valor del código que tiene asignado el transportista el cual debe contener alguna de las claves contenidas en el catálogo correspondiente.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar el valor del código que tiene asignado el trans" +
            "portista el cual debe contener alguna de las claves contenidas en el catálogo co" +
            "rrespondiente.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("CodigoTransportista")]
        public string CodigoTransportista { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar el RFC del embarcador de los bienes y/o mercancías que se trasladan.</para>
        /// <para>Tipo definido para expresar claves del Registro Federal de Contribuyentes</para>
        /// <para xml:lang="en">Minimum length: 12.</para>
        /// <para xml:lang="en">Maximum length: 13.</para>
        /// <para xml:lang="en">Pattern: [A-Z&Ñ]{3,4}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A].</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para registrar el RFC del embarcador de los bienes y/o mercancí" +
            "as que se trasladan.")]
        [MinLengthAttribute(12)]
        [MaxLengthAttribute(13)]
        [RegularExpressionAttribute("[A-Z&Ñ]{3,4}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A]")]
        [XmlAttributeAttribute("RFCEmbarcador")]
        public string RfcEmbarcador { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para incorporar el número de identificación o registro fiscal del país de residencia cuando el embarcador sea residente en el extranjero para los efectos fiscales correspondientes de los bienes y/o mercancías que se trasladan.</para>
        /// <para xml:lang="en">Minimum length: 6.</para>
        /// <para xml:lang="en">Maximum length: 40.</para>
        /// <para xml:lang="en">Pattern: [^|]{6,40}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para incorporar el número de identificación o registro fisca" +
            "l del país de residencia cuando el embarcador sea residente en el extranjero par" +
            "a los efectos fiscales correspondientes de los bienes y/o mercancías que se tras" +
            "ladan.")]
        [MinLengthAttribute(6)]
        [MaxLengthAttribute(40)]
        [RegularExpressionAttribute("[^|]{6,40}")]
        [XmlAttributeAttribute("NumRegIdTribEmbarc")]
        public string NumRegIdTribEmbarc { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar la clave del país de residencia para efectos fiscales del embarcador de los bienes y/o mercancías.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar la clave del país de residencia para efectos " +
            "fiscales del embarcador de los bienes y/o mercancías.")]
        [XmlAttributeAttribute("ResidenciaFiscalEmbarc")]
        public string ResidenciaFiscalEmbarc { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar el nombre del embarcador de los bienes y/o mercancías que se trasladan, ya sea nacional o extranjero.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 254.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,254}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para registrar el nombre del embarcador de los bienes y/o merca" +
            "ncías que se trasladan, ya sea nacional o extranjero.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(254)]
        [RegularExpressionAttribute("[^|]{1,254}")]
        [XmlAttributeAttribute("NombreEmbarcador")]
        public string NombreEmbarcador { get; set; }
    }
}
