//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v30
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteMercanciasAutotransporteRemolquesRemolque", Namespace="http://www.sat.gob.mx/CartaPorte30", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("CartaPorteMercanciasAutotransporteRemolquesRemolque", Namespace="http://www.sat.gob.mx/CartaPorte30")]
    public partial class CartaPorteMercanciasAutotransporteRemolquesRemolque
    {
        
        /// <summary>
        /// <para>Atributo requerido para expresar la clave del subtipo de remolque o semirremolques que se emplean con el autotransporte para el traslado de los bienes y/o mercancías.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar la clave del subtipo de remolque o semirremolque" +
            "s que se emplean con el autotransporte para el traslado de los bienes y/o mercan" +
            "cías.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("SubTipoRem")]
        public string SubTipoRem { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar los caracteres alfanuméricos, sin guiones ni espacios de la placa vehicular del remolque o semirremolque que es utilizado para transportar los bienes y/o mercancías.</para>
        /// <para xml:lang="en">Pattern: [^(?!.*\s)-]{5,7}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar los caracteres alfanuméricos, sin guiones ni es" +
            "pacios de la placa vehicular del remolque o semirremolque que es utilizado para " +
            "transportar los bienes y/o mercancías.")]
        [RegularExpressionAttribute("[^(?!.*\\s)-]{5,7}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Placa")]
        public string Placa { get; set; }
    }
}
