//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v30
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteMercanciasAutotransporteSeguros", Namespace="http://www.sat.gob.mx/CartaPorte30", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("CartaPorteMercanciasAutotransporteSeguros", Namespace="http://www.sat.gob.mx/CartaPorte30")]
    public partial class CartaPorteMercanciasAutotransporteSeguros
    {
        
        /// <summary>
        /// <para>Atributo requerido para registrar el nombre de la aseguradora que cubre los riesgos por responsabilidad civil del autotransporte utilizado para el traslado de los bienes y/o mercancías.</para>
        /// <para xml:lang="en">Minimum length: 3.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [^|]{3,50}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar el nombre de la aseguradora que cubre los riesg" +
            "os por responsabilidad civil del autotransporte utilizado para el traslado de lo" +
            "s bienes y/o mercancías.")]
        [MinLengthAttribute(3)]
        [MaxLengthAttribute(50)]
        [RegularExpressionAttribute("[^|]{3,50}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("AseguraRespCivil")]
        public string AseguraRespCivil { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar el número de póliza asignado por la aseguradora, que cubre los riesgos por responsabilidad civil del autotransporte utilizado para el traslado de los bienes y/o mercancías.</para>
        /// <para xml:lang="en">Minimum length: 3.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// <para xml:lang="en">Pattern: [^|]{3,30}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar el número de póliza asignado por la aseguradora" +
            ", que cubre los riesgos por responsabilidad civil del autotransporte utilizado p" +
            "ara el traslado de los bienes y/o mercancías.")]
        [MinLengthAttribute(3)]
        [MaxLengthAttribute(30)]
        [RegularExpressionAttribute("[^|]{3,30}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("PolizaRespCivil")]
        public string PolizaRespCivil { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar el nombre de la aseguradora, que cubre los posibles daños al medio ambiente cuando exista al menos una mercancía tipificada como material peligroso se debe registrar la información del atributo “AseguraMedAmbiente” (aplicable para los transportistas de materiales, residuos o remanentes y desechos peligrosos.</para>
        /// <para xml:lang="en">Minimum length: 3.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [^|]{3,50}.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para registrar el nombre de la aseguradora, que cubre los posibles daños al medio ambiente cuando exista al menos una mercancía tipificada como material peligroso se debe registrar la información del atributo “AseguraMedAmbiente” (aplicable para los transportistas de materiales, residuos o remanentes y desechos peligrosos.")]
        [MinLengthAttribute(3)]
        [MaxLengthAttribute(50)]
        [RegularExpressionAttribute("[^|]{3,50}")]
        [XmlAttributeAttribute("AseguraMedAmbiente")]
        public string AseguraMedAmbiente { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar el número de póliza asignado por la aseguradora, que cubre los posibles daños al medio ambiente cuando exista al menos una mercancía tipificada como material peligroso se debe registrar la información del atributo “AseguraMedAmbiente” (aplicable para los transportistas de materiales, residuos o remanentes y desechos peligrosos).</para>
        /// <para xml:lang="en">Minimum length: 3.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// <para xml:lang="en">Pattern: [^|]{3,30}.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para registrar el número de póliza asignado por la aseguradora, que cubre los posibles daños al medio ambiente cuando exista al menos una mercancía tipificada como material peligroso se debe registrar la información del atributo “AseguraMedAmbiente” (aplicable para los transportistas de materiales, residuos o remanentes y desechos peligrosos).")]
        [MinLengthAttribute(3)]
        [MaxLengthAttribute(30)]
        [RegularExpressionAttribute("[^|]{3,30}")]
        [XmlAttributeAttribute("PolizaMedAmbiente")]
        public string PolizaMedAmbiente { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar el nombre de la aseguradora que cubre los riesgos de la carga (bienes y/o mercancías) del autotransporte utilizado para el traslado.</para>
        /// <para xml:lang="en">Minimum length: 3.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [^|]{3,50}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para registrar el nombre de la aseguradora que cubre los riesgo" +
            "s de la carga (bienes y/o mercancías) del autotransporte utilizado para el trasl" +
            "ado.")]
        [MinLengthAttribute(3)]
        [MaxLengthAttribute(50)]
        [RegularExpressionAttribute("[^|]{3,50}")]
        [XmlAttributeAttribute("AseguraCarga")]
        public string AseguraCarga { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para expresar el número de póliza asignado por la aseguradora que cubre los riesgos de la carga (bienes y/o mercancías) del autotransporte utilizado para el traslado.</para>
        /// <para xml:lang="en">Minimum length: 3.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// <para xml:lang="en">Pattern: [^|]{3,30}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para expresar el número de póliza asignado por la aseguradora q" +
            "ue cubre los riesgos de la carga (bienes y/o mercancías) del autotransporte util" +
            "izado para el traslado.")]
        [MinLengthAttribute(3)]
        [MaxLengthAttribute(30)]
        [RegularExpressionAttribute("[^|]{3,30}")]
        [XmlAttributeAttribute("PolizaCarga")]
        public string PolizaCarga { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar el valor del importe por el cargo adicional convenido entre el transportista y el cliente, el cual será igual al valor de la prima del seguro contratado, conforme a lo establecido en la cláusula novena del Acuerdo por el que se homologa la Carta de Porte regulada por la Ley de Caminos, Puentes y Autotransporte Federal, con el complemento Carta Porte que debe acompañar al Comprobante Fiscal Digital por Internet (CFDI).</para>
        /// <para>Tipo definido para expresar importes numéricos con fracción hasta seis decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.000000.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,6})?.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo opcional para registrar el valor del importe por el cargo adicional convenido entre el transportista y el cliente, el cual será igual al valor de la prima del seguro contratado, conforme a lo establecido en la cláusula novena del Acuerdo por el que se homologa la Carta de Porte regulada por la Ley de Caminos, Puentes y Autotransporte Federal, con el complemento Carta Porte que debe acompañar al Comprobante Fiscal Digital por Internet (CFDI).")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,6})?")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("PrimaSeguro")]
        public decimal PrimaSeguroValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the PrimaSeguro property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool PrimaSeguroValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar el valor del importe por el cargo adicional convenido entre el transportista y el cliente, el cual será igual al valor de la prima del seguro contratado, conforme a lo establecido en la cláusula novena del Acuerdo por el que se homologa la Carta de Porte regulada por la Ley de Caminos, Puentes y Autotransporte Federal, con el complemento Carta Porte que debe acompañar al Comprobante Fiscal Digital por Internet (CFDI).</para>
        /// <para>Tipo definido para expresar importes numéricos con fracción hasta seis decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.000000.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,6})?.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<decimal> PrimaSeguro
        {
            get
            {
                if (this.PrimaSeguroValueSpecified)
                {
                    return this.PrimaSeguroValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.PrimaSeguroValue = value.GetValueOrDefault();
                this.PrimaSeguroValueSpecified = value.HasValue;
            }
        }
    }
}
