//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/nomina=Nomina.v11 resources/sitio_internet/cfd/nomina/nomina11.xsd
namespace JAMS.SAT.CFDI.Xml.Nomina.v11
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("NominaIncapacidadesIncapacidad", Namespace="http://www.sat.gob.mx/nomina", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class NominaIncapacidadesIncapacidad
    {
        
        /// <summary>
        /// <para>Número de días que el trabajador se incapacitó en el periodo</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// </summary>
        [DescriptionAttribute("Número de días que el trabajador se incapacitó en el periodo")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("DiasIncapacidad")]
        public decimal DiasIncapacidad { get; set; }
        
        /// <summary>
        /// <para>Razón de la incapacidad: Catálogo publicado en el portal del SAT en internet</para>
        /// </summary>
        [DescriptionAttribute("Razón de la incapacidad: Catálogo publicado en el portal del SAT en internet")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TipoIncapacidad")]
        public int TipoIncapacidad { get; set; }
        
        /// <summary>
        /// <para>Monto del descuento por la incapacidad</para>
        /// <para>Tipo definido para expresar importes numéricos con fracción hasta seis decimales</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// </summary>
        [DescriptionAttribute("Monto del descuento por la incapacidad")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Descuento")]
        public decimal Descuento { get; set; }
    }
}
