//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/nomina=Nomina.v11 resources/sitio_internet/cfd/nomina/nomina11.xsd
namespace JAMS.SAT.CFDI.Xml.Nomina.v11
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Complemento al Comprobante Fiscal Digital a través de Internet (CFDI) para el manejo de datos de Nómina.</para>
    /// </summary>
    [DescriptionAttribute("Complemento al Comprobante Fiscal Digital a través de Internet (CFDI) para el man" +
        "ejo de datos de Nómina.")]
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Nomina", Namespace="http://www.sat.gob.mx/nomina", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("Nomina", Namespace="http://www.sat.gob.mx/nomina")]
    public partial class Nomina
    {
        
        /// <summary>
        /// <para>Nodo opcional para expresar las percepciones aplicables</para>
        /// </summary>
        [DescriptionAttribute("Nodo opcional para expresar las percepciones aplicables")]
        [XmlElementAttribute("Percepciones")]
        public NominaPercepciones Percepciones { get; set; }
        
        /// <summary>
        /// <para>Nodo opcional para expresar las deducciones aplicables</para>
        /// </summary>
        [DescriptionAttribute("Nodo opcional para expresar las deducciones aplicables")]
        [XmlElementAttribute("Deducciones")]
        public NominaDeducciones Deducciones { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<NominaIncapacidadesIncapacidad> _incapacidades;
        
        /// <summary>
        /// <para>Nodo opcional para expresar las incapacidades aplicables</para>
        /// </summary>
        [DescriptionAttribute("Nodo opcional para expresar las incapacidades aplicables")]
        [XmlArrayAttribute("Incapacidades")]
        [XmlArrayItemAttribute("Incapacidad", Namespace="http://www.sat.gob.mx/nomina")]
        public Collection<NominaIncapacidadesIncapacidad> Incapacidades
        {
            get
            {
                return _incapacidades;
            }
            private set
            {
                _incapacidades = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Incapacidades collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool IncapacidadesSpecified
        {
            get
            {
                return (this.Incapacidades.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Nomina" /> class.</para>
        /// </summary>
        public Nomina()
        {
            this._incapacidades = new Collection<NominaIncapacidadesIncapacidad>();
            this._horasExtras = new Collection<NominaHorasExtrasHorasExtra>();
        }
        
        [XmlIgnoreAttribute()]
        private Collection<NominaHorasExtrasHorasExtra> _horasExtras;
        
        /// <summary>
        /// <para>Nodo opcional para expresar las horas extras aplicables</para>
        /// </summary>
        [DescriptionAttribute("Nodo opcional para expresar las horas extras aplicables")]
        [XmlArrayAttribute("HorasExtras")]
        [XmlArrayItemAttribute("HorasExtra", Namespace="http://www.sat.gob.mx/nomina")]
        public Collection<NominaHorasExtrasHorasExtra> HorasExtras
        {
            get
            {
                return _horasExtras;
            }
            private set
            {
                _horasExtras = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the HorasExtras collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool HorasExtrasSpecified
        {
            get
            {
                return (this.HorasExtras.Count != 0);
            }
        }
        
        [XmlIgnoreAttribute()]
        private string _version = "1.1";
        
        /// <summary>
        /// <para>Atributo requerido para la expresión de la versión del complemento</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para la expresión de la versión del complemento")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
        
        /// <summary>
        /// <para>Atributo opcional para expresar el registro patronal a 20 posiciones máximo</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para expresar el registro patronal a 20 posiciones máximo")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(20)]
        [XmlAttributeAttribute("RegistroPatronal")]
        public string RegistroPatronal { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el número de empleado de 1 a 15 posiciones</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el número de empleado de 1 a 15 posiciones")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(15)]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("NumEmpleado")]
        public string NumEmpleado { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para la expresión de la CURP del trabajador</para>
        /// <para>Tipo definido para la expresión de una CURP</para>
        /// <para xml:lang="en">Minimum length: 18.</para>
        /// <para xml:lang="en">Maximum length: 18.</para>
        /// <para xml:lang="en">Pattern: [A-Z][A,E,I,O,U,X][A-Z]{2}[0-9]{2}[0-1][0-9][0-3][0-9][M,H][A-Z]{2}[B,C,D,F,G,H,J,K,L,M,N,Ñ,P,Q,R,S,T,V,W,X,Y,Z]{3}[0-9,A-Z][0-9].</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para la expresión de la CURP del trabajador")]
        [MinLengthAttribute(18)]
        [MaxLengthAttribute(18)]
        [RegularExpressionAttribute("[A-Z][A,E,I,O,U,X][A-Z]{2}[0-9]{2}[0-1][0-9][0-3][0-9][M,H][A-Z]{2}[B,C,D,F,G,H,J" +
            ",K,L,M,N,Ñ,P,Q,R,S,T,V,W,X,Y,Z]{3}[0-9,A-Z][0-9]")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("CURP")]
        public string Curp { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para la expresión de la clave del régimen por el cual se tiene contratado al trabajador, conforme al catálogo publicado en el portal del SAT en internet</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para la expresión de la clave del régimen por el cual se tiene" +
            " contratado al trabajador, conforme al catálogo publicado en el portal del SAT e" +
            "n internet")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TipoRegimen")]
        public int TipoRegimen { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para la expresión del número de seguridad social aplicable al trabajador</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para la expresión del número de seguridad social aplicable al t" +
            "rabajador")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(15)]
        [XmlAttributeAttribute("NumSeguridadSocial")]
        public string NumSeguridadSocial { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para la expresión de la fecha efectiva de erogación del gasto. Se expresa en la forma aaaa-mm-dd, de acuerdo con la especificación ISO 8601.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para la expresión de la fecha efectiva de erogación del gasto." +
            " Se expresa en la forma aaaa-mm-dd, de acuerdo con la especificación ISO 8601.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("FechaPago", DataType="date")]
        public DateTime FechaPago { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para la expresión de la fecha inicial del pago. Se expresa en la forma aaaa-mm-dd, de acuerdo con la especificación ISO 8601.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para la expresión de la fecha inicial del pago. Se expresa en " +
            "la forma aaaa-mm-dd, de acuerdo con la especificación ISO 8601.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("FechaInicialPago", DataType="date")]
        public DateTime FechaInicialPago { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para la expresión de la fecha final del pago. Se expresa en la forma aaaa-mm-dd, de acuerdo con la especificación ISO 8601.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para la expresión de la fecha final del pago. Se expresa en la" +
            " forma aaaa-mm-dd, de acuerdo con la especificación ISO 8601.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("FechaFinalPago", DataType="date")]
        public DateTime FechaFinalPago { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para la expresión del número de días pagados</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para la expresión del número de días pagados")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("NumDiasPagados")]
        public decimal NumDiasPagados { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para la expresión del departamento o área a la que pertenece el trabajador</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para la expresión del departamento o área a la que pertenece el" +
            " trabajador")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(100)]
        [XmlAttributeAttribute("Departamento")]
        public string Departamento { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para la expresión de la CLABE</para>
        /// <para>Tipo definido para expresar la CLABE interbancaria</para>
        /// <para xml:lang="en">Pattern: [0-9]{18}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para la expresión de la CLABE")]
        [RegularExpressionAttribute("[0-9]{18}")]
        [XmlAttributeAttribute("CLABE")]
        public string Clabe { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para la expresión del Banco conforme al catálogo, donde se realiza un depósito de nómina</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Pattern: [0-9]{3}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para la expresión del Banco conforme al catálogo, donde se real" +
            "iza un depósito de nómina")]
        [RegularExpressionAttribute("[0-9]{3}")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("Banco")]
        public int BancoValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Banco property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool BancoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para la expresión del Banco conforme al catálogo, donde se realiza un depósito de nómina</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Pattern: [0-9]{3}.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<int> Banco
        {
            get
            {
                if (this.BancoValueSpecified)
                {
                    return this.BancoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.BancoValue = value.GetValueOrDefault();
                this.BancoValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Atributo opcional para expresar la fecha de inicio de la relación laboral entre el empleador y el empleado</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para expresar la fecha de inicio de la relación laboral entre e" +
            "l empleador y el empleado")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("FechaInicioRelLaboral", DataType="date")]
        public DateTime FechaInicioRelLaboralValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the FechaInicioRelLaboral property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool FechaInicioRelLaboralValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para expresar la fecha de inicio de la relación laboral entre el empleador y el empleado</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<DateTime> FechaInicioRelLaboral
        {
            get
            {
                if (this.FechaInicioRelLaboralValueSpecified)
                {
                    return this.FechaInicioRelLaboralValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.FechaInicioRelLaboralValue = value.GetValueOrDefault();
                this.FechaInicioRelLaboralValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Número de semanas que el empleado ha mantenido relación laboral con el empleador</para>
        /// </summary>
        [DescriptionAttribute("Número de semanas que el empleado ha mantenido relación laboral con el empleador")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("Antiguedad")]
        public int AntiguedadValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Antiguedad property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool AntiguedadValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Número de semanas que el empleado ha mantenido relación laboral con el empleador</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<int> Antiguedad
        {
            get
            {
                if (this.AntiguedadValueSpecified)
                {
                    return this.AntiguedadValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AntiguedadValue = value.GetValueOrDefault();
                this.AntiguedadValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Puesto asignado al empleado o actividad que realiza</para>
        /// </summary>
        [DescriptionAttribute("Puesto asignado al empleado o actividad que realiza")]
        [XmlAttributeAttribute("Puesto")]
        public string Puesto { get; set; }
        
        /// <summary>
        /// <para>Tipo de contrato que tiene el trabajador: Base, Eventual, Confianza, Sindicalizado, a prueba, etc.</para>
        /// </summary>
        [DescriptionAttribute("Tipo de contrato que tiene el trabajador: Base, Eventual, Confianza, Sindicalizad" +
            "o, a prueba, etc.")]
        [XmlAttributeAttribute("TipoContrato")]
        public string TipoContrato { get; set; }
        
        /// <summary>
        /// <para>Tipo de jornada que cubre el trabajador: Diurna, nocturna, mixta, por hora, reducida, continuada, partida, por turnos, etc.</para>
        /// </summary>
        [DescriptionAttribute("Tipo de jornada que cubre el trabajador: Diurna, nocturna, mixta, por hora, reduc" +
            "ida, continuada, partida, por turnos, etc.")]
        [XmlAttributeAttribute("TipoJornada")]
        public string TipoJornada { get; set; }
        
        /// <summary>
        /// <para>Forma en que se establece el pago del salario: diario, semanal, quincenal, catorcenal mensual, bimestral, unidad de obra, comisión, precio alzado, etc.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// </summary>
        [DescriptionAttribute("Forma en que se establece el pago del salario: diario, semanal, quincenal, catorc" +
            "enal mensual, bimestral, unidad de obra, comisión, precio alzado, etc.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(100)]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("PeriodicidadPago")]
        public string PeriodicidadPago { get; set; }
        
        /// <summary>
        /// <para>Retribución otorgada al trabajador, que se integra por los pagos hechos en efectivo por cuota diaria, gratificaciones, percepciones, alimentación, habitación, primas, comisiones, prestaciones en especie y cualquiera otra cantidad o prestación que se entregue al trabajador por su trabajo, sin considerar los conceptos que se excluyen de conformidad con el Artículo 27 de la Ley del Seguro Social. (Se emplea para pagar las cuotas y aportaciones de Seguridad Social).</para>
        /// <para>Tipo definido para expresar importes numéricos con fracción hasta seis decimales</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// </summary>
        [DescriptionAttribute(@"Retribución otorgada al trabajador, que se integra por los pagos hechos en efectivo por cuota diaria, gratificaciones, percepciones, alimentación, habitación, primas, comisiones, prestaciones en especie y cualquiera otra cantidad o prestación que se entregue al trabajador por su trabajo, sin considerar los conceptos que se excluyen de conformidad con el Artículo 27 de la Ley del Seguro Social. (Se emplea para pagar las cuotas y aportaciones de Seguridad Social).")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("SalarioBaseCotApor")]
        public decimal SalarioBaseCotAporValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SalarioBaseCotApor property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool SalarioBaseCotAporValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Retribución otorgada al trabajador, que se integra por los pagos hechos en efectivo por cuota diaria, gratificaciones, percepciones, alimentación, habitación, primas, comisiones, prestaciones en especie y cualquiera otra cantidad o prestación que se entregue al trabajador por su trabajo, sin considerar los conceptos que se excluyen de conformidad con el Artículo 27 de la Ley del Seguro Social. (Se emplea para pagar las cuotas y aportaciones de Seguridad Social).</para>
        /// <para>Tipo definido para expresar importes numéricos con fracción hasta seis decimales</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<decimal> SalarioBaseCotApor
        {
            get
            {
                if (this.SalarioBaseCotAporValueSpecified)
                {
                    return this.SalarioBaseCotAporValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SalarioBaseCotAporValue = value.GetValueOrDefault();
                this.SalarioBaseCotAporValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Clave conforme a la Clase en que deben inscribirse los patrones, de acuerdo a las actividades que desempeñan sus trabajadores, según lo previsto en el artículo 196 del Reglamento en Materia de Afiliación Clasificación de Empresas, Recaudación y Fiscalización. Catálogo publicado en el portal del SAT en internet</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// </summary>
        [DescriptionAttribute(@"Clave conforme a la Clase en que deben inscribirse los patrones, de acuerdo a las actividades que desempeñan sus trabajadores, según lo previsto en el artículo 196 del Reglamento en Materia de Afiliación Clasificación de Empresas, Recaudación y Fiscalización. Catálogo publicado en el portal del SAT en internet")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("RiesgoPuesto")]
        public int RiesgoPuestoValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the RiesgoPuesto property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool RiesgoPuestoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Clave conforme a la Clase en que deben inscribirse los patrones, de acuerdo a las actividades que desempeñan sus trabajadores, según lo previsto en el artículo 196 del Reglamento en Materia de Afiliación Clasificación de Empresas, Recaudación y Fiscalización. Catálogo publicado en el portal del SAT en internet</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<int> RiesgoPuesto
        {
            get
            {
                if (this.RiesgoPuestoValueSpecified)
                {
                    return this.RiesgoPuestoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.RiesgoPuestoValue = value.GetValueOrDefault();
                this.RiesgoPuestoValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>El salario se integra con los pagos hechos en efectivo por cuota diaria, gratificaciones, percepciones, habitación, primas, comisiones, prestaciones en especie y cualquiera otra cantidad o prestación que se entregue al trabajador por su trabajo, de conformidad con el Art. 84 de la Ley Federal del Trabajo. (Se utiliza para el cálculo de las indemnizaciones).</para>
        /// <para>Tipo definido para expresar importes numéricos con fracción hasta seis decimales</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// </summary>
        [DescriptionAttribute(@"El salario se integra con los pagos hechos en efectivo por cuota diaria, gratificaciones, percepciones, habitación, primas, comisiones, prestaciones en especie y cualquiera otra cantidad o prestación que se entregue al trabajador por su trabajo, de conformidad con el Art. 84 de la Ley Federal del Trabajo. (Se utiliza para el cálculo de las indemnizaciones).")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("SalarioDiarioIntegrado")]
        public decimal SalarioDiarioIntegradoValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SalarioDiarioIntegrado property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool SalarioDiarioIntegradoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>El salario se integra con los pagos hechos en efectivo por cuota diaria, gratificaciones, percepciones, habitación, primas, comisiones, prestaciones en especie y cualquiera otra cantidad o prestación que se entregue al trabajador por su trabajo, de conformidad con el Art. 84 de la Ley Federal del Trabajo. (Se utiliza para el cálculo de las indemnizaciones).</para>
        /// <para>Tipo definido para expresar importes numéricos con fracción hasta seis decimales</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<decimal> SalarioDiarioIntegrado
        {
            get
            {
                if (this.SalarioDiarioIntegradoValueSpecified)
                {
                    return this.SalarioDiarioIntegradoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SalarioDiarioIntegradoValue = value.GetValueOrDefault();
                this.SalarioDiarioIntegradoValueSpecified = value.HasValue;
            }
        }
    }
}
