//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/nomina=Nomina.v11 resources/sitio_internet/cfd/nomina/nomina11.xsd
namespace JAMS.SAT.CFDI.Xml.Nomina.v11
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("NominaPercepciones", Namespace="http://www.sat.gob.mx/nomina", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class NominaPercepciones
    {
        
        [XmlIgnoreAttribute()]
        private Collection<NominaPercepcionesPercepcion> _percepcion;
        
        /// <summary>
        /// <para>Nodo para expresar la información detallada de una percepción</para>
        /// </summary>
        [DescriptionAttribute("Nodo para expresar la información detallada de una percepción")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Percepcion")]
        public Collection<NominaPercepcionesPercepcion> Percepcion
        {
            get
            {
                return _percepcion;
            }
            private set
            {
                _percepcion = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="NominaPercepciones" /> class.</para>
        /// </summary>
        public NominaPercepciones()
        {
            this._percepcion = new Collection<NominaPercepcionesPercepcion>();
        }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el total de percepciones gravadas que se relacionan en el comprobante</para>
        /// <para>Tipo definido para expresar importes numéricos con fracción hasta seis decimales</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el total de percepciones gravadas que se relacio" +
            "nan en el comprobante")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TotalGravado")]
        public decimal TotalGravado { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el total de percepciones exentas que se relacionan en el comprobante</para>
        /// <para>Tipo definido para expresar importes numéricos con fracción hasta seis decimales</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el total de percepciones exentas que se relacion" +
            "an en el comprobante")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TotalExento")]
        public decimal TotalExento { get; set; }
    }
}
