//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/nomina=Nomina.v11 resources/sitio_internet/cfd/nomina/nomina11.xsd
namespace JAMS.SAT.CFDI.Xml.Nomina.v11
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("NominaIncapacidades", Namespace="http://www.sat.gob.mx/nomina", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class NominaIncapacidades
    {
        
        [XmlIgnoreAttribute()]
        private Collection<NominaIncapacidadesIncapacidad> _incapacidad;
        
        /// <summary>
        /// <para>Nodo opcional para expresar información de las incapacidades</para>
        /// </summary>
        [DescriptionAttribute("Nodo opcional para expresar información de las incapacidades")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Incapacidad")]
        public Collection<NominaIncapacidadesIncapacidad> Incapacidad
        {
            get
            {
                return _incapacidad;
            }
            private set
            {
                _incapacidad = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="NominaIncapacidades" /> class.</para>
        /// </summary>
        public NominaIncapacidades()
        {
            this._incapacidad = new Collection<NominaIncapacidadesIncapacidad>();
        }
    }
}
