//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/ecc=ECC resources/sitio_internet/cfd/ecc/ecc.xsd
namespace JAMS.SAT.CFDI.Xml.ECC
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("EstadoDeCuentaCombustibleConceptosConceptoEstadoDeCuentaCombustibleTrasladosTrasl" +
        "ado", Namespace="http://www.sat.gob.mx/ecc", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class EstadoDeCuentaCombustibleConceptosConceptoEstadoDeCuentaCombustibleTrasladosTraslado
    {
        
        /// <summary>
        /// <para>Atributo requerido para definir el tipo de impuesto trasladado</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para definir el tipo de impuesto trasladado")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("impuesto")]
        public string Impuesto { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para señalar la tasa del impuesto que se traslada por cada concepto amparado en el comprobante</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para señalar la tasa del impuesto que se traslada por cada con" +
            "cepto amparado en el comprobante")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("tasa")]
        public decimal Tasa { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para definir el importe o monto del impuesto trasladado</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para definir el importe o monto del impuesto trasladado")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("importe")]
        public decimal Importe { get; set; }
    }
}
