//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/divisas=Divisas resources/sitio_internet/cfd/divisas/divisas.xsd
namespace JAMS.SAT.CFDI.Xml.Divisas
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Complemento al Comprobante Fiscal Digital (CFD) y Comprobante Fiscal Digital por Internet (CFDI) para identificar las operaciones de compra y  venta de divisas que realizan los centros cambiarios y las casa de cambio; haciendo mención expresa de que los comprobantes se expiden por la “compra”, o bien, por la “venta” de divisas.</para>
    /// </summary>
    [DescriptionAttribute(@"Complemento al Comprobante Fiscal Digital (CFD) y Comprobante Fiscal Digital por Internet (CFDI) para identificar las operaciones de compra y venta de divisas que realizan los centros cambiarios y las casa de cambio; haciendo mención expresa de que los comprobantes se expiden por la “compra”, o bien, por la “venta” de divisas.")]
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Divisas", Namespace="http://www.sat.gob.mx/divisas", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("Divisas", Namespace="http://www.sat.gob.mx/divisas")]
    public partial class Divisas
    {
        
        [XmlIgnoreAttribute()]
        private string _version = "1.0";
        
        /// <summary>
        /// <para>Atributo requerido para expresar la versión del complemento de divisas</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar la versión del complemento de divisas")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
        
        /// <summary>
        /// <para>Elemento para definir el tipo de operación realizada. venta o compra de divisas</para>
        /// </summary>
        [DescriptionAttribute("Elemento para definir el tipo de operación realizada. venta o compra de divisas")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("tipoOperacion")]
        public string TipoOperacion { get; set; }
    }
}
