//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/ComercioExterior20/ComercioExterior20.xsd
namespace JAMS.SAT.CFDI.Xml.ComercioExterior.v20
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ComercioExteriorDestinatario", Namespace="http://www.sat.gob.mx/ComercioExterior20", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ComercioExteriorDestinatario
    {
        
        [XmlIgnoreAttribute()]
        private Collection<ComercioExteriorDestinatarioDomicilio> _domicilio;
        
        /// <summary>
        /// <para>Nodo requerido para expresar el domicilio del destinatario de la mercancía.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para expresar el domicilio del destinatario de la mercancía.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Domicilio")]
        public Collection<ComercioExteriorDestinatarioDomicilio> Domicilio
        {
            get
            {
                return _domicilio;
            }
            private set
            {
                _domicilio = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ComercioExteriorDestinatario" /> class.</para>
        /// </summary>
        public ComercioExteriorDestinatario()
        {
            this._domicilio = new Collection<ComercioExteriorDestinatarioDomicilio>();
        }
        
        /// <summary>
        /// <para>Atributo opcional para incorporar el número de identificación o registro fiscal del país de residencia para efectos fiscales del destinatario de la mercancía exportada.</para>
        /// <para xml:lang="en">Minimum length: 6.</para>
        /// <para xml:lang="en">Maximum length: 40.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para incorporar el número de identificación o registro fiscal d" +
            "el país de residencia para efectos fiscales del destinatario de la mercancía exp" +
            "ortada.")]
        [MinLengthAttribute(6)]
        [MaxLengthAttribute(40)]
        [XmlAttributeAttribute("NumRegIdTrib")]
        public string NumRegIdTrib { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para expresar el nombre completo, denominación o razón social del destinatario de la mercancía exportada.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 300.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,300}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para expresar el nombre completo, denominación o razón social d" +
            "el destinatario de la mercancía exportada.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(300)]
        [RegularExpressionAttribute("[^|]{1,300}")]
        [XmlAttributeAttribute("Nombre")]
        public string Nombre { get; set; }
    }
}
