//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/ComercioExterior20/ComercioExterior20.xsd
namespace JAMS.SAT.CFDI.Xml.ComercioExterior.v20
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ComercioExteriorMercancias", Namespace="http://www.sat.gob.mx/ComercioExterior20", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ComercioExteriorMercancias
    {
        
        [XmlIgnoreAttribute()]
        private Collection<ComercioExteriorMercanciasMercancia> _mercancia;
        
        /// <summary>
        /// <para>Nodo requerido para capturar la información de la declaración de cada mercancía exportada.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para capturar la información de la declaración de cada mercancía e" +
            "xportada.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Mercancia")]
        public Collection<ComercioExteriorMercanciasMercancia> Mercancia
        {
            get
            {
                return _mercancia;
            }
            private set
            {
                _mercancia = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ComercioExteriorMercancias" /> class.</para>
        /// </summary>
        public ComercioExteriorMercancias()
        {
            this._mercancia = new Collection<ComercioExteriorMercanciasMercancia>();
        }
    }
}
