//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/ComercioExterior20/ComercioExterior20.xsd
namespace JAMS.SAT.CFDI.Xml.ComercioExterior.v20
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ComercioExteriorDestinatarioDomicilio", Namespace="http://www.sat.gob.mx/ComercioExterior20", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ComercioExteriorDestinatarioDomicilio
    {
        
        /// <summary>
        /// <para>Atributo requerido que sirve para precisar la calle en que está ubicado el domicilio del destinatario de la mercancía.</para>
        /// <para>Tipo definido para expresar la calle en que está ubicado el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,100}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido que sirve para precisar la calle en que está ubicado el domici" +
            "lio del destinatario de la mercancía.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(100)]
        [RegularExpressionAttribute("[^|]{1,100}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Calle")]
        public string Calle { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional que sirve para expresar el número exterior en donde se ubica el domicilio del destinatario de la mercancía.</para>
        /// <para>Tipo definido para expresar el número interior o el número exterior en donde se ubica el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 55.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,55}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional que sirve para expresar el número exterior en donde se ubica el" +
            " domicilio del destinatario de la mercancía.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(55)]
        [RegularExpressionAttribute("[^|]{1,55}")]
        [XmlAttributeAttribute("NumeroExterior")]
        public string NumeroExterior { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional que sirve para expresar el número interior, en caso de existir, en donde se ubica el domicilio del destinatario de la mercancía.</para>
        /// <para>Tipo definido para expresar el número interior o el número exterior en donde se ubica el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 55.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,55}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional que sirve para expresar el número interior, en caso de existir," +
            " en donde se ubica el domicilio del destinatario de la mercancía.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(55)]
        [RegularExpressionAttribute("[^|]{1,55}")]
        [XmlAttributeAttribute("NumeroInterior")]
        public string NumeroInterior { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional que sirve para expresar la colonia o dato análogo en donde se ubica el domicilio del destinatario de la mercancía.</para>
        /// <para>Tipo definido para expresar la colonia, localidad o municipio en que está ubicado el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 120.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,120}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional que sirve para expresar la colonia o dato análogo en donde se u" +
            "bica el domicilio del destinatario de la mercancía.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(120)]
        [RegularExpressionAttribute("[^|]{1,120}")]
        [XmlAttributeAttribute("Colonia")]
        public string Colonia { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional que sirve para precisar la ciudad, población, distrito u otro análogo en donde se ubica el domicilio del destinatario de la mercancía.</para>
        /// <para>Tipo definido para expresar la colonia, localidad o municipio en que está ubicado el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 120.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,120}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional que sirve para precisar la ciudad, población, distrito u otro a" +
            "nálogo en donde se ubica el domicilio del destinatario de la mercancía.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(120)]
        [RegularExpressionAttribute("[^|]{1,120}")]
        [XmlAttributeAttribute("Localidad")]
        public string Localidad { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar una referencia geográfica adicional que permita una  fácil o precisa ubicación del domicilio del destinatario de la mercancía, por ejemplo las coordenadas GPS.</para>
        /// <para>Tipo definido para expresar la referencia geográfica adicional que permita una  fácil o precisa ubicación del domicilio del emisor del comprobante o del destinatario de la mercancía, por ejemplo las coordenadas GPS.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 250.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,250}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para registrar una referencia geográfica adicional que permita " +
            "una fácil o precisa ubicación del domicilio del destinatario de la mercancía, po" +
            "r ejemplo las coordenadas GPS.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(250)]
        [RegularExpressionAttribute("[^|]{1,250}")]
        [XmlAttributeAttribute("Referencia")]
        public string Referencia { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional que sirve para precisar el municipio, delegación o alcaldía, condado o dato análogo en donde se encuentra ubicado el destinatario de la mercancía.</para>
        /// <para>Tipo definido para expresar la colonia, localidad o municipio en que está ubicado el domicilio del emisor del comprobante o del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 120.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,120}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional que sirve para precisar el municipio, delegación o alcaldía, co" +
            "ndado o dato análogo en donde se encuentra ubicado el destinatario de la mercanc" +
            "ía.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(120)]
        [RegularExpressionAttribute("[^|]{1,120}")]
        [XmlAttributeAttribute("Municipio")]
        public string Municipio { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para señalar el estado, entidad, región, comunidad u otra figura análoga en donde se encuentra ubicado el domicilio del destinatario de la mercancía. El catálogo se publica en el Portal del SAT en internet y es conforme con la especificación ISO 3166-2.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,30}.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo requerido para señalar el estado, entidad, región, comunidad u otra figura análoga en donde se encuentra ubicado el domicilio del destinatario de la mercancía. El catálogo se publica en el Portal del SAT en internet y es conforme con la especificación ISO 3166-2.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(30)]
        [RegularExpressionAttribute("[^|]{1,30}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Estado")]
        public string Estado { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido que sirve para precisar la clave del país donde se encuentra ubicado el destinatario de la mercancía, conforme con el catálogo c_Pais publicado en el Portal del SAT en internet que está basado en la especificación ISO 3166-1.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido que sirve para precisar la clave del país donde se encuentra u" +
            "bicado el destinatario de la mercancía, conforme con el catálogo c_Pais publicad" +
            "o en el Portal del SAT en internet que está basado en la especificación ISO 3166" +
            "-1.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Pais")]
        public string Pais { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido que sirve para registrar el código postal en donde se encuentra ubicado el domicilio del destinatario de la mercancía.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 12.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido que sirve para registrar el código postal en donde se encuentr" +
            "a ubicado el domicilio del destinatario de la mercancía.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(12)]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("CodigoPostal")]
        public string CodigoPostal { get; set; }
    }
}
