//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v20
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteUbicacionesUbicacion", Namespace="http://www.sat.gob.mx/CartaPorte20", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("CartaPorteUbicacionesUbicacion", Namespace="http://www.sat.gob.mx/CartaPorte20")]
    public partial class CartaPorteUbicacionesUbicacion
    {
        
        /// <summary>
        /// <para>Nodo condicional para registrar información del domicilio de origen y/o destino de los bienes y/o mercancías que se trasladan a través de los distintos medios de transporte.</para>
        /// </summary>
        [DescriptionAttribute("Nodo condicional para registrar información del domicilio de origen y/o destino d" +
            "e los bienes y/o mercancías que se trasladan a través de los distintos medios de" +
            " transporte.")]
        [XmlElementAttribute("Domicilio")]
        public CartaPorteUbicacionesUbicacionDomicilio Domicilio { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para precisar si el tipo de ubicación corresponde al origen o destino de las ubicaciones para el traslado de los bienes y/o mercancías en los distintos medios de transporte.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para precisar si el tipo de ubicación corresponde al origen o " +
            "destino de las ubicaciones para el traslado de los bienes y/o mercancías en los " +
            "distintos medios de transporte.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TipoUbicacion")]
        public string TipoUbicacion { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar una clave que sirva para identificar el punto de salida o entrada de los bienes y/o mercancías que se trasladan a través de los distintos medios de transporte, la cual estará integrada de la siguiente forma: para origen el acrónimo “OR” o para destino el acrónimo “DE” seguido de 6 dígitos numéricos asignados por el contribuyente que emite el comprobante para su identificación.</para>
        /// <para xml:lang="en">Pattern: (OR|DE)[0-9]{6}.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para registrar una clave que sirva para identificar el punto de salida o entrada de los bienes y/o mercancías que se trasladan a través de los distintos medios de transporte, la cual estará integrada de la siguiente forma: para origen el acrónimo “OR” o para destino el acrónimo “DE” seguido de 6 dígitos numéricos asignados por el contribuyente que emite el comprobante para su identificación.")]
        [RegularExpressionAttribute("(OR|DE)[0-9]{6}")]
        [XmlAttributeAttribute("IDUbicacion")]
        public string IdUbicacion { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar el RFC del remitente o destinatario de los bienes y/o mercancías que se trasladan a través de los distintos medios de transporte.</para>
        /// <para>Tipo definido para expresar claves del Registro Federal de Contribuyentes</para>
        /// <para xml:lang="en">Minimum length: 12.</para>
        /// <para xml:lang="en">Maximum length: 13.</para>
        /// <para xml:lang="en">Pattern: [A-Z&Ñ]{3,4}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A].</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar el RFC del remitente o destinatario de los bien" +
            "es y/o mercancías que se trasladan a través de los distintos medios de transport" +
            "e.")]
        [MinLengthAttribute(12)]
        [MaxLengthAttribute(13)]
        [RegularExpressionAttribute("[A-Z&Ñ]{3,4}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A]")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("RFCRemitenteDestinatario")]
        public string RfcRemitenteDestinatario { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar el nombre del remitente o destinatario de los bienes y/o mercancías que se trasladan a través de los distintos medios de transporte.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 254.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,254}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para registrar el nombre del remitente o destinatario de los bi" +
            "enes y/o mercancías que se trasladan a través de los distintos medios de transpo" +
            "rte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(254)]
        [RegularExpressionAttribute("[^|]{1,254}")]
        [XmlAttributeAttribute("NombreRemitenteDestinatario")]
        public string NombreRemitenteDestinatario { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar el número de identificación o registro fiscal del país de residencia, para los efectos fiscales del remitente o destinatario de los bienes y/o mercancías que se trasladan cuando se trate de residentes en el extranjero.</para>
        /// <para xml:lang="en">Minimum length: 6.</para>
        /// <para xml:lang="en">Maximum length: 40.</para>
        /// <para xml:lang="en">Pattern: [^|]{6,40}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar el número de identificación o registro fiscal" +
            " del país de residencia, para los efectos fiscales del remitente o destinatario " +
            "de los bienes y/o mercancías que se trasladan cuando se trate de residentes en e" +
            "l extranjero.")]
        [MinLengthAttribute(6)]
        [MaxLengthAttribute(40)]
        [RegularExpressionAttribute("[^|]{6,40}")]
        [XmlAttributeAttribute("NumRegIdTrib")]
        public string NumRegIdTrib { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar la clave del país de residencia para efectos fiscales del remitente o destinatario de los bienes y/o mercancías, conforme el catálogo de CFDI c_Pais publicado en el portal del SAT en Internet de acuerdo a la especificación ISO 3166-1.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para registrar la clave del país de residencia para efectos fiscales del remitente o destinatario de los bienes y/o mercancías, conforme el catálogo de CFDI c_Pais publicado en el portal del SAT en Internet de acuerdo a la especificación ISO 3166-1.")]
        [XmlAttributeAttribute("ResidenciaFiscal")]
        public string ResidenciaFiscal { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar la clave de la estación de origen o destino para el traslado de los bienes y/o mercancías que se realiza a través de los distintos medios de transporte, esto de acuerdo al valor de la columna “Clave identificación” del catálogo c_Estaciones del complemento Carta Porte que permita asociarla al tipo de transporte.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para registrar la clave de la estación de origen o destino para el traslado de los bienes y/o mercancías que se realiza a través de los distintos medios de transporte, esto de acuerdo al valor de la columna “Clave identificación” del catálogo c_Estaciones del complemento Carta Porte que permita asociarla al tipo de transporte.")]
        [XmlAttributeAttribute("NumEstacion")]
        public string NumEstacion { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar el nombre de la estación de origen o destino por la que se pasa para efectuar el traslado de los bienes y/o mercancías a través de los distintos medios de transporte, conforme al catálogo c_Estaciones del complemento Carta Porte.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,50}.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para registrar el nombre de la estación de origen o destino por la que se pasa para efectuar el traslado de los bienes y/o mercancías a través de los distintos medios de transporte, conforme al catálogo c_Estaciones del complemento Carta Porte.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(50)]
        [RegularExpressionAttribute("[^|]{1,50}")]
        [XmlAttributeAttribute("NombreEstacion")]
        public string NombreEstacion { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar el tipo de puerto de origen o destino en el cual se documentan los bienes y/o mercancías que se trasladan vía marítima.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar el tipo de puerto de origen o destino en el c" +
            "ual se documentan los bienes y/o mercancías que se trasladan vía marítima.")]
        [XmlAttributeAttribute("NavegacionTrafico")]
        public string NavegacionTrafico { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar la fecha y hora estimada en la que salen o llegan los bienes y/o mercancías de origen o al destino, respectivamente. Se expresa en la forma AAAA-MM-DDThh:mm:ss.</para>
        /// <para>Tipo definido para la expresión de la fecha y hora. Se expresa en la forma AAAA-MM-DDThh:mm:ss</para>
        /// <para xml:lang="en">Pattern: (20[1-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]).</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar la fecha y hora estimada en la que salen o lleg" +
            "an los bienes y/o mercancías de origen o al destino, respectivamente. Se expresa" +
            " en la forma AAAA-MM-DDThh:mm:ss.")]
        [RegularExpressionAttribute("(20[1-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5]" +
            "[0-9]:[0-5][0-9])")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("FechaHoraSalidaLlegada", DataType="dateTime")]
        public DateTime FechaHoraSalidaLlegada { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar el tipo de estación por el que pasan los bienes y/o mercancías durante su traslado a través de los distintos medios de transporte.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar el tipo de estación por el que pasan los bien" +
            "es y/o mercancías durante su traslado a través de los distintos medios de transp" +
            "orte.")]
        [XmlAttributeAttribute("TipoEstacion")]
        public string TipoEstacion { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar en kilómetros la distancia recorrida entre la ubicación de origen y la de destino parcial o final, por los distintos medios de transporte que trasladan los bienes y/o mercancías.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.01.</para>
        /// <para xml:lang="en">Maximum inclusive value: 99999.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para registrar en kilómetros la distancia recorrida entre la" +
            " ubicación de origen y la de destino parcial o final, por los distintos medios d" +
            "e transporte que trasladan los bienes y/o mercancías.")]
        [RangeAttribute(typeof(decimal), "0.01", "99999", ParseLimitsInInvariantCulture=true, ConvertValueInInvariantCulture=true)]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("DistanciaRecorrida")]
        public decimal DistanciaRecorridaValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the DistanciaRecorrida property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool DistanciaRecorridaValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar en kilómetros la distancia recorrida entre la ubicación de origen y la de destino parcial o final, por los distintos medios de transporte que trasladan los bienes y/o mercancías.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.01.</para>
        /// <para xml:lang="en">Maximum inclusive value: 99999.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<decimal> DistanciaRecorrida
        {
            get
            {
                if (this.DistanciaRecorridaValueSpecified)
                {
                    return this.DistanciaRecorridaValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DistanciaRecorridaValue = value.GetValueOrDefault();
                this.DistanciaRecorridaValueSpecified = value.HasValue;
            }
        }
    }
}
