//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v20
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteFiguraTransporte", Namespace="http://www.sat.gob.mx/CartaPorte20", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("CartaPorteFiguraTransporte", Namespace="http://www.sat.gob.mx/CartaPorte20")]
    public partial class CartaPorteFiguraTransporte
    {
        
        [XmlIgnoreAttribute()]
        private Collection<CartaPorteFiguraTransporteTiposFigura> _tiposFigura;
        
        /// <summary>
        /// <para>Nodo condicional para indicar los datos del(los) tipo(s) de figura(s) que participan en el traslado de los bienes y/o mercancías en los distintos medios de transporte.</para>
        /// </summary>
        [DescriptionAttribute("Nodo condicional para indicar los datos del(los) tipo(s) de figura(s) que partici" +
            "pan en el traslado de los bienes y/o mercancías en los distintos medios de trans" +
            "porte.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("TiposFigura")]
        public Collection<CartaPorteFiguraTransporteTiposFigura> TiposFigura
        {
            get
            {
                return _tiposFigura;
            }
            private set
            {
                _tiposFigura = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CartaPorteFiguraTransporte" /> class.</para>
        /// </summary>
        public CartaPorteFiguraTransporte()
        {
            this._tiposFigura = new Collection<CartaPorteFiguraTransporteTiposFigura>();
        }
    }
}
