//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt resources/sitio_internet/cfd/CartaPorte/CartaPorte.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd resources/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd
namespace JAMS.SAT.CFDI.Xml.CartaPorte.v20
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CartaPorteMercanciasTransporteMaritimoContenedor", Namespace="http://www.sat.gob.mx/CartaPorte20", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("CartaPorteMercanciasTransporteMaritimoContenedor", Namespace="http://www.sat.gob.mx/CartaPorte20")]
    public partial class CartaPorteMercanciasTransporteMaritimoContenedor
    {
        
        /// <summary>
        /// <para>Atributo requerido para registrar la matrícula o el número de identificación del contenedor marítimo en el que se transportan los bienes y/o mercancías, el cual está integrado por el código del propietario, el número de serie y el dígito de control correspondiente.</para>
        /// <para xml:lang="en">Minimum length: 11.</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// <para xml:lang="en">Pattern: [^|]{11,15}.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo requerido para registrar la matrícula o el número de identificación del contenedor marítimo en el que se transportan los bienes y/o mercancías, el cual está integrado por el código del propietario, el número de serie y el dígito de control correspondiente.")]
        [MinLengthAttribute(11)]
        [MaxLengthAttribute(15)]
        [RegularExpressionAttribute("[^|]{11,15}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("MatriculaContenedor")]
        public string MatriculaContenedor { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar la clave de identificación correspondiente con el tipo de contenedor marítimo en el que se transportan los bienes y/o mercancías.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar la clave de identificación correspondiente con " +
            "el tipo de contenedor marítimo en el que se transportan los bienes y/o mercancía" +
            "s.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TipoContenedor")]
        public string TipoContenedor { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar el número del sello o precinto de los contenedores marítimos que son utilizados para trasladar los bienes y/o mercancías.</para>
        /// <para xml:lang="en">Minimum length: 5.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// <para xml:lang="en">Pattern: [^|]{5,20}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para registrar el número del sello o precinto de los contenedor" +
            "es marítimos que son utilizados para trasladar los bienes y/o mercancías.")]
        [MinLengthAttribute(5)]
        [MaxLengthAttribute(20)]
        [RegularExpressionAttribute("[^|]{5,20}")]
        [XmlAttributeAttribute("NumPrecinto")]
        public string NumPrecinto { get; set; }
    }
}
