//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/EstadoDeCuentaCombustible=EstadoCuentaCombustible.v12 resources/sitio_internet/cfd/EstadoDeCuentaCombustible/ecc12.xsd
namespace JAMS.SAT.CFDI.Xml.EstadoDeCuentaCombustible12
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Complemento para el Comprobante Fiscal Digital por Internet (CFDI) para integrar la información aplicable al estado de cuenta emitido por un prestador de servicios de monedero electrónico</para>
    /// </summary>
    [DescriptionAttribute("Complemento para el Comprobante Fiscal Digital por Internet (CFDI) para integrar " +
        "la información aplicable al estado de cuenta emitido por un prestador de servici" +
        "os de monedero electrónico")]
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("EstadoDeCuentaCombustible", Namespace="http://www.sat.gob.mx/EstadoDeCuentaCombustible12", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("EstadoDeCuentaCombustible", Namespace="http://www.sat.gob.mx/EstadoDeCuentaCombustible12")]
    public partial class EstadoDeCuentaCombustible
    {
        
        [XmlIgnoreAttribute()]
        private Collection<EstadoDeCuentaCombustibleConceptosConceptoEstadoDeCuentaCombustible> _conceptos;
        
        /// <summary>
        /// <para>Nodo requerido para enlistar los conceptos cubiertos por Estado de Cuenta de Combustible.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para enlistar los conceptos cubiertos por Estado de Cuenta de Comb" +
            "ustible.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlArrayAttribute("Conceptos")]
        [XmlArrayItemAttribute("ConceptoEstadoDeCuentaCombustible", Namespace="http://www.sat.gob.mx/EstadoDeCuentaCombustible12")]
        public Collection<EstadoDeCuentaCombustibleConceptosConceptoEstadoDeCuentaCombustible> Conceptos
        {
            get
            {
                return _conceptos;
            }
            private set
            {
                _conceptos = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="EstadoDeCuentaCombustible" /> class.</para>
        /// </summary>
        public EstadoDeCuentaCombustible()
        {
            this._conceptos = new Collection<EstadoDeCuentaCombustibleConceptosConceptoEstadoDeCuentaCombustible>();
        }
        
        [XmlIgnoreAttribute()]
        private string _version = "1.2";
        
        /// <summary>
        /// <para>Atributo requerido que indica la versión del complemento.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido que indica la versión del complemento.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private string _tipoOperacion = "Tarjeta";
        
        /// <summary>
        /// <para>Atributo requerido para expresar el tipo de operación de acuerdo con el medio de pago.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el tipo de operación de acuerdo con el medio de " +
            "pago.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TipoOperacion")]
        public string TipoOperacion
        {
            get
            {
                return _tipoOperacion;
            }
            set
            {
                _tipoOperacion = value;
            }
        }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el número de cuenta del adquirente del monedero electrónico</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el número de cuenta del adquirente del monedero " +
            "electrónico")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(50)]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("NumeroDeCuenta")]
        public string NumeroDeCuenta { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para representar la suma de todos los importes tipo ConceptoEstadoDeCuentaCombustible.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,14}(.([0-9]{1,2})).</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para representar la suma de todos los importes tipo ConceptoEs" +
            "tadoDeCuentaCombustible.")]
        [RegularExpressionAttribute("[0-9]{1,14}(.([0-9]{1,2}))")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("SubTotal")]
        public decimal SubTotal { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el monto total de consumo de combustible.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,14}(.([0-9]{1,2})).</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el monto total de consumo de combustible.")]
        [RegularExpressionAttribute("[0-9]{1,14}(.([0-9]{1,2}))")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Total")]
        public decimal Total { get; set; }
    }
}
