//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/nomina=Nomina.v12 resources/sitio_internet/cfd/nomina/nomina12.xsd
namespace JAMS.SAT.CFDI.Xml.Nomina12
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("NominaOtrosPagos", Namespace="http://www.sat.gob.mx/nomina12", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class NominaOtrosPagos
    {
        
        [XmlIgnoreAttribute()]
        private Collection<NominaOtrosPagosOtroPago> _otroPago;
        
        /// <summary>
        /// <para>Nodo requerido para expresar la información detallada del otro pago.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para expresar la información detallada del otro pago.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("OtroPago")]
        public Collection<NominaOtrosPagosOtroPago> OtroPago
        {
            get
            {
                return _otroPago;
            }
            private set
            {
                _otroPago = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="NominaOtrosPagos" /> class.</para>
        /// </summary>
        public NominaOtrosPagos()
        {
            this._otroPago = new Collection<NominaOtrosPagosOtroPago>();
        }
    }
}
