//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/nomina=Nomina.v12 resources/sitio_internet/cfd/nomina/nomina12.xsd
namespace JAMS.SAT.CFDI.Xml.Nomina12
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("NominaReceptor", Namespace="http://www.sat.gob.mx/nomina12", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class NominaReceptor
    {
        
        [XmlIgnoreAttribute()]
        private Collection<NominaReceptorSubContratacion> _subContratacion;
        
        /// <summary>
        /// <para>Nodo condicional para expresar la lista de las personas que los subcontrataron.</para>
        /// </summary>
        [DescriptionAttribute("Nodo condicional para expresar la lista de las personas que los subcontrataron.")]
        [XmlElementAttribute("SubContratacion")]
        public Collection<NominaReceptorSubContratacion> SubContratacion
        {
            get
            {
                return _subContratacion;
            }
            private set
            {
                _subContratacion = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the SubContratacion collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool SubContratacionSpecified
        {
            get
            {
                return (this.SubContratacion.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="NominaReceptor" /> class.</para>
        /// </summary>
        public NominaReceptor()
        {
            this._subContratacion = new Collection<NominaReceptorSubContratacion>();
        }
        
        /// <summary>
        /// <para>Atributo requerido para expresar la CURP del receptor del comprobante de nómina.</para>
        /// <para>Tipo definido para expresar la Clave Única de Registro de Población (CURP)</para>
        /// <para xml:lang="en">Minimum length: 18.</para>
        /// <para xml:lang="en">Maximum length: 18.</para>
        /// <para xml:lang="en">Pattern: [A-Z][AEIOUX][A-Z]{2}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[MH]([ABCMTZ]S|[BCJMOT]C|[CNPST]L|[GNQ]T|[GQS]R|C[MH]|[MY]N|[DH]G|NE|VZ|DF|SP)[BCDFGHJ-NP-TV-Z]{3}[0-9A-Z][0-9].</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar la CURP del receptor del comprobante de nómina.")]
        [MinLengthAttribute(18)]
        [MaxLengthAttribute(18)]
        [RegularExpressionAttribute("[A-Z][AEIOUX][A-Z]{2}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[MH]([ABCMTZ]" +
            "S|[BCJMOT]C|[CNPST]L|[GNQ]T|[GQS]R|C[MH]|[MY]N|[DH]G|NE|VZ|DF|SP)[BCDFGHJ-NP-TV-" +
            "Z]{3}[0-9A-Z][0-9]")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Curp")]
        public string Curp { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el número de seguridad social del trabajador. Se debe ingresar cuando se cuente con él, o se esté obligado conforme a otras disposiciones distintas a las fiscales.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,15}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar el número de seguridad social del trabajador. " +
            "Se debe ingresar cuando se cuente con él, o se esté obligado conforme a otras di" +
            "sposiciones distintas a las fiscales.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(15)]
        [RegularExpressionAttribute("[0-9]{1,15}")]
        [XmlAttributeAttribute("NumSeguridadSocial")]
        public string NumSeguridadSocial { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar la fecha de inicio de la relación laboral entre el empleador y el empleado. Se expresa en la forma AAAA-MM-DD, de acuerdo con la especificación ISO 8601. Se debe ingresar cuando se cuente con él, o se esté obligado conforme a otras disposiciones distintas a las fiscales.</para>
        /// <para>Tipo definido para la expresión de la fecha. Se expresa en la forma AAAA-MM-DD.</para>
        /// <para xml:lang="en">Pattern: ((19|20)[0-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]).</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para expresar la fecha de inicio de la relación laboral entre el empleador y el empleado. Se expresa en la forma AAAA-MM-DD, de acuerdo con la especificación ISO 8601. Se debe ingresar cuando se cuente con él, o se esté obligado conforme a otras disposiciones distintas a las fiscales.")]
        [RegularExpressionAttribute("((19|20)[0-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("FechaInicioRelLaboral", DataType="date")]
        public DateTime FechaInicioRelLaboralValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the FechaInicioRelLaboral property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool FechaInicioRelLaboralValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar la fecha de inicio de la relación laboral entre el empleador y el empleado. Se expresa en la forma AAAA-MM-DD, de acuerdo con la especificación ISO 8601. Se debe ingresar cuando se cuente con él, o se esté obligado conforme a otras disposiciones distintas a las fiscales.</para>
        /// <para>Tipo definido para la expresión de la fecha. Se expresa en la forma AAAA-MM-DD.</para>
        /// <para xml:lang="en">Pattern: ((19|20)[0-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]).</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<DateTime> FechaInicioRelLaboral
        {
            get
            {
                if (this.FechaInicioRelLaboralValueSpecified)
                {
                    return this.FechaInicioRelLaboralValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.FechaInicioRelLaboralValue = value.GetValueOrDefault();
                this.FechaInicioRelLaboralValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el número de semanas o el periodo de años, meses y días que el empleado ha mantenido relación laboral con el empleador. Se debe ingresar cuando se cuente con él, o se esté obligado conforme a otras disposiciones distintas a las fiscales.</para>
        /// <para xml:lang="en">Pattern: P(([1-9][0-9]{0,3})|0)W|P([1-9][0-9]?Y)?(([1-9]|1[012])M)?(0|[1-9]|[12][0-9]|3[01])D.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para expresar el número de semanas o el periodo de años, meses y días que el empleado ha mantenido relación laboral con el empleador. Se debe ingresar cuando se cuente con él, o se esté obligado conforme a otras disposiciones distintas a las fiscales.")]
        [RegularExpressionAttribute("P(([1-9][0-9]{0,3})|0)W|P([1-9][0-9]?Y)?(([1-9]|1[012])M)?(0|[1-9]|[12][0-9]|3[01" +
            "])D")]
        [XmlAttributeAttribute("Antigüedad")]
        public string Antigüedad { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el tipo de contrato que tiene el trabajador.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el tipo de contrato que tiene el trabajador.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TipoContrato")]
        public string TipoContrato { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para indicar si el trabajador está asociado a un sindicato. Si se omite se asume que no está asociado a algún sindicato.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para indicar si el trabajador está asociado a un sindicato. Si " +
            "se omite se asume que no está asociado a algún sindicato.")]
        [XmlAttributeAttribute("Sindicalizado")]
        public string Sindicalizado { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el tipo de jornada que cubre el trabajador. Se debe ingresar cuando se esté obligado conforme a otras disposiciones distintas a las fiscales.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar el tipo de jornada que cubre el trabajador. Se" +
            " debe ingresar cuando se esté obligado conforme a otras disposiciones distintas " +
            "a las fiscales.")]
        [XmlAttributeAttribute("TipoJornada")]
        public string TipoJornada { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para la expresión de la clave del régimen por el cual se tiene contratado al trabajador.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para la expresión de la clave del régimen por el cual se tiene" +
            " contratado al trabajador.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TipoRegimen")]
        public string TipoRegimen { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el número de empleado de 1 a 15 posiciones.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,15}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el número de empleado de 1 a 15 posiciones.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(15)]
        [RegularExpressionAttribute("[^|]{1,15}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("NumEmpleado")]
        public string NumEmpleado { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para la expresión del departamento o área a la que pertenece el trabajador.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,100}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para la expresión del departamento o área a la que pertenece el" +
            " trabajador.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(100)]
        [RegularExpressionAttribute("[^|]{1,100}")]
        [XmlAttributeAttribute("Departamento")]
        public string Departamento { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para la expresión del puesto asignado al empleado o actividad que realiza.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,100}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para la expresión del puesto asignado al empleado o actividad q" +
            "ue realiza.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(100)]
        [RegularExpressionAttribute("[^|]{1,100}")]
        [XmlAttributeAttribute("Puesto")]
        public string Puesto { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para expresar la clave conforme a la Clase en que deben inscribirse los patrones, de acuerdo con las actividades que desempeñan sus trabajadores, según lo previsto en el artículo 196 del Reglamento en Materia de Afiliación Clasificación de Empresas, Recaudación y Fiscalización, o conforme con la normatividad del Instituto de Seguridad Social del trabajador.  Se debe ingresar cuando se cuente con él, o se esté obligado conforme a otras disposiciones distintas a las fiscales.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo opcional para expresar la clave conforme a la Clase en que deben inscribirse los patrones, de acuerdo con las actividades que desempeñan sus trabajadores, según lo previsto en el artículo 196 del Reglamento en Materia de Afiliación Clasificación de Empresas, Recaudación y Fiscalización, o conforme con la normatividad del Instituto de Seguridad Social del trabajador. Se debe ingresar cuando se cuente con él, o se esté obligado conforme a otras disposiciones distintas a las fiscales.")]
        [XmlAttributeAttribute("RiesgoPuesto")]
        public string RiesgoPuesto { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para la forma en que se establece el pago del salario.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para la forma en que se establece el pago del salario.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("PeriodicidadPago")]
        public string PeriodicidadPago { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para la expresión de la clave del Banco conforme al catálogo, donde se realiza el depósito de nómina.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para la expresión de la clave del Banco conforme al catálogo" +
            ", donde se realiza el depósito de nómina.")]
        [XmlAttributeAttribute("Banco")]
        public string Banco { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para la expresión de la cuenta bancaria a 11 posiciones o número de teléfono celular a 10 posiciones o número de tarjeta de crédito, débito o servicios a 15 ó 16 posiciones o la CLABE a 18 posiciones o número de monedero electrónico, donde se realiza el depósito de nómina.</para>
        /// <para>Tipo definido para expresar la cuenta bancarizada.</para>
        /// <para xml:lang="en">Pattern: [0-9]{10,18}.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para la expresión de la cuenta bancaria a 11 posiciones o número de teléfono celular a 10 posiciones o número de tarjeta de crédito, débito o servicios a 15 ó 16 posiciones o la CLABE a 18 posiciones o número de monedero electrónico, donde se realiza el depósito de nómina.")]
        [RegularExpressionAttribute("[0-9]{10,18}")]
        [XmlAttributeAttribute("CuentaBancaria")]
        public string CuentaBancaria { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para expresar la retribución otorgada al trabajador, que se integra por los pagos hechos en efectivo por cuota diaria, gratificaciones, percepciones, alimentación, habitación, primas, comisiones, prestaciones en especie y cualquiera otra cantidad o prestación que se entregue al trabajador por su trabajo, sin considerar los conceptos que se excluyen de conformidad con el Artículo 27 de la Ley del Seguro Social, o la integración de los pagos conforme la normatividad del Instituto de Seguridad Social del trabajador. (Se emplea para pagar las cuotas y aportaciones de Seguridad Social). Se debe ingresar cuando se esté obligado conforme a otras disposiciones distintas a las fiscales.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo opcional para expresar la retribución otorgada al trabajador, que se integra por los pagos hechos en efectivo por cuota diaria, gratificaciones, percepciones, alimentación, habitación, primas, comisiones, prestaciones en especie y cualquiera otra cantidad o prestación que se entregue al trabajador por su trabajo, sin considerar los conceptos que se excluyen de conformidad con el Artículo 27 de la Ley del Seguro Social, o la integración de los pagos conforme la normatividad del Instituto de Seguridad Social del trabajador. (Se emplea para pagar las cuotas y aportaciones de Seguridad Social). Se debe ingresar cuando se esté obligado conforme a otras disposiciones distintas a las fiscales.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,2})?")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("SalarioBaseCotApor")]
        public decimal SalarioBaseCotAporValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SalarioBaseCotApor property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool SalarioBaseCotAporValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para expresar la retribución otorgada al trabajador, que se integra por los pagos hechos en efectivo por cuota diaria, gratificaciones, percepciones, alimentación, habitación, primas, comisiones, prestaciones en especie y cualquiera otra cantidad o prestación que se entregue al trabajador por su trabajo, sin considerar los conceptos que se excluyen de conformidad con el Artículo 27 de la Ley del Seguro Social, o la integración de los pagos conforme la normatividad del Instituto de Seguridad Social del trabajador. (Se emplea para pagar las cuotas y aportaciones de Seguridad Social). Se debe ingresar cuando se esté obligado conforme a otras disposiciones distintas a las fiscales.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<decimal> SalarioBaseCotApor
        {
            get
            {
                if (this.SalarioBaseCotAporValueSpecified)
                {
                    return this.SalarioBaseCotAporValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SalarioBaseCotAporValue = value.GetValueOrDefault();
                this.SalarioBaseCotAporValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Atributo opcional para expresar el salario que se integra con los pagos hechos en efectivo por cuota diaria, gratificaciones, percepciones, habitación, primas, comisiones, prestaciones en especie y cualquier otra cantidad o prestación que se entregue al trabajador por su trabajo, de conformidad con el Art. 84 de la Ley Federal del Trabajo. (Se utiliza para el cálculo de las indemnizaciones). Se debe ingresar cuando se esté obligado conforme a otras disposiciones distintas a las fiscales.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo opcional para expresar el salario que se integra con los pagos hechos en efectivo por cuota diaria, gratificaciones, percepciones, habitación, primas, comisiones, prestaciones en especie y cualquier otra cantidad o prestación que se entregue al trabajador por su trabajo, de conformidad con el Art. 84 de la Ley Federal del Trabajo. (Se utiliza para el cálculo de las indemnizaciones). Se debe ingresar cuando se esté obligado conforme a otras disposiciones distintas a las fiscales.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,2})?")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("SalarioDiarioIntegrado")]
        public decimal SalarioDiarioIntegradoValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SalarioDiarioIntegrado property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool SalarioDiarioIntegradoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para expresar el salario que se integra con los pagos hechos en efectivo por cuota diaria, gratificaciones, percepciones, habitación, primas, comisiones, prestaciones en especie y cualquier otra cantidad o prestación que se entregue al trabajador por su trabajo, de conformidad con el Art. 84 de la Ley Federal del Trabajo. (Se utiliza para el cálculo de las indemnizaciones). Se debe ingresar cuando se esté obligado conforme a otras disposiciones distintas a las fiscales.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<decimal> SalarioDiarioIntegrado
        {
            get
            {
                if (this.SalarioDiarioIntegradoValueSpecified)
                {
                    return this.SalarioDiarioIntegradoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SalarioDiarioIntegradoValue = value.GetValueOrDefault();
                this.SalarioDiarioIntegradoValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Atributo requerido para expresar la clave de la entidad federativa en donde el receptor del recibo prestó el servicio.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar la clave de la entidad federativa en donde el re" +
            "ceptor del recibo prestó el servicio.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("ClaveEntFed")]
        public string ClaveEntFed { get; set; }
    }
}
