//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/nomina=Nomina.v12 resources/sitio_internet/cfd/nomina/nomina12.xsd
namespace JAMS.SAT.CFDI.Xml.Nomina12
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("NominaPercepcionesJubilacionPensionRetiro", Namespace="http://www.sat.gob.mx/nomina12", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class NominaPercepcionesJubilacionPensionRetiro
    {
        
        /// <summary>
        /// <para>Atributo condicional que indica el monto total del pago cuando se realiza en una sola exhibición.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional que indica el monto total del pago cuando se realiza en una " +
            "sola exhibición.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,2})?")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("TotalUnaExhibicion")]
        public decimal TotalUnaExhibicionValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TotalUnaExhibicion property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool TotalUnaExhibicionValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional que indica el monto total del pago cuando se realiza en una sola exhibición.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<decimal> TotalUnaExhibicion
        {
            get
            {
                if (this.TotalUnaExhibicionValueSpecified)
                {
                    return this.TotalUnaExhibicionValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TotalUnaExhibicionValue = value.GetValueOrDefault();
                this.TotalUnaExhibicionValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Atributo condicional para expresar los ingresos totales por pago cuando se hace en parcialidades.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar los ingresos totales por pago cuando se hace e" +
            "n parcialidades.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,2})?")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("TotalParcialidad")]
        public decimal TotalParcialidadValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TotalParcialidad property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool TotalParcialidadValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar los ingresos totales por pago cuando se hace en parcialidades.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<decimal> TotalParcialidad
        {
            get
            {
                if (this.TotalParcialidadValueSpecified)
                {
                    return this.TotalParcialidadValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TotalParcialidadValue = value.GetValueOrDefault();
                this.TotalParcialidadValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el monto diario percibido por jubilación, pensiones o haberes de retiro cuando se realiza en parcialidades.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar el monto diario percibido por jubilación, pens" +
            "iones o haberes de retiro cuando se realiza en parcialidades.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,2})?")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("MontoDiario")]
        public decimal MontoDiarioValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MontoDiario property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool MontoDiarioValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el monto diario percibido por jubilación, pensiones o haberes de retiro cuando se realiza en parcialidades.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<decimal> MontoDiario
        {
            get
            {
                if (this.MontoDiarioValueSpecified)
                {
                    return this.MontoDiarioValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.MontoDiarioValue = value.GetValueOrDefault();
                this.MontoDiarioValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Atributo requerido para expresar los ingresos acumulables.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar los ingresos acumulables.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,2})?")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("IngresoAcumulable")]
        public decimal IngresoAcumulable { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar los ingresos no acumulables.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar los ingresos no acumulables.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,2})?")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("IngresoNoAcumulable")]
        public decimal IngresoNoAcumulable { get; set; }
    }
}
