//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/nomina=Nomina.v12 resources/sitio_internet/cfd/nomina/nomina12.xsd
namespace JAMS.SAT.CFDI.Xml.Nomina12
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("NominaEmisorEntidadSncf", Namespace="http://www.sat.gob.mx/nomina12", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class NominaEmisorEntidadSncf
    {
        
        /// <summary>
        /// <para>Atributo requerido para identificar el origen del recurso utilizado para el pago de nómina del personal que presta o desempeña un servicio personal subordinado o asimilado a salarios en las dependencias.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para identificar el origen del recurso utilizado para el pago " +
            "de nómina del personal que presta o desempeña un servicio personal subordinado o" +
            " asimilado a salarios en las dependencias.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("OrigenRecurso")]
        public string OrigenRecurso { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el monto del recurso pagado con cargo a sus participaciones u otros ingresos locales (importe bruto de los ingresos propios, es decir total de gravados y exentos), cuando el origen es mixto.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar el monto del recurso pagado con cargo a sus pa" +
            "rticipaciones u otros ingresos locales (importe bruto de los ingresos propios, e" +
            "s decir total de gravados y exentos), cuando el origen es mixto.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,2})?")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("MontoRecursoPropio")]
        public decimal MontoRecursoPropioValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MontoRecursoPropio property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool MontoRecursoPropioValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el monto del recurso pagado con cargo a sus participaciones u otros ingresos locales (importe bruto de los ingresos propios, es decir total de gravados y exentos), cuando el origen es mixto.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<decimal> MontoRecursoPropio
        {
            get
            {
                if (this.MontoRecursoPropioValueSpecified)
                {
                    return this.MontoRecursoPropioValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.MontoRecursoPropioValue = value.GetValueOrDefault();
                this.MontoRecursoPropioValueSpecified = value.HasValue;
            }
        }
    }
}
