//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/nomina=Nomina.v12 resources/sitio_internet/cfd/nomina/nomina12.xsd
namespace JAMS.SAT.CFDI.Xml.Nomina12
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("NominaDeduccionesDeduccion", Namespace="http://www.sat.gob.mx/nomina12", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class NominaDeduccionesDeduccion
    {
        
        /// <summary>
        /// <para>Atributo requerido para registrar la clave agrupadora que clasifica la deducción.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar la clave agrupadora que clasifica la deducción." +
            "")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TipoDeduccion")]
        public string TipoDeduccion { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para la clave de deducción de nómina propia de la contabilidad de cada patrón, puede conformarse desde 3 hasta 15 caracteres.</para>
        /// <para xml:lang="en">Minimum length: 3.</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// <para xml:lang="en">Pattern: [^|]{3,15}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para la clave de deducción de nómina propia de la contabilidad" +
            " de cada patrón, puede conformarse desde 3 hasta 15 caracteres.")]
        [MinLengthAttribute(3)]
        [MaxLengthAttribute(15)]
        [RegularExpressionAttribute("[^|]{3,15}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Clave")]
        public string Clave { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para la descripción del concepto de deducción.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,100}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para la descripción del concepto de deducción.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(100)]
        [RegularExpressionAttribute("[^|]{1,100}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Concepto")]
        public string Concepto { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para registrar el importe del concepto de deducción.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para registrar el importe del concepto de deducción.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,2})?")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Importe")]
        public decimal Importe { get; set; }
    }
}
