//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/nomina=Nomina.v12 resources/sitio_internet/cfd/nomina/nomina12.xsd
namespace JAMS.SAT.CFDI.Xml.Nomina12
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("NominaPercepcionesSeparacionIndemnizacion", Namespace="http://www.sat.gob.mx/nomina12", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class NominaPercepcionesSeparacionIndemnizacion
    {
        
        /// <summary>
        /// <para>Atributo requerido que indica el monto total del pago.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido que indica el monto total del pago.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,2})?")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TotalPagado")]
        public decimal TotalPagado { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el número de años de servicio del trabajador. Se redondea al entero superior si la cifra contiene años y meses y hay más de 6 meses.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Maximum inclusive value: 99.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el número de años de servicio del trabajador. Se" +
            " redondea al entero superior si la cifra contiene años y meses y hay más de 6 me" +
            "ses.")]
        [RangeAttribute(typeof(int), "0", "99")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("NumAñosServicio")]
        public int NumAñosServicio { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido que indica el último sueldo mensual ordinario.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido que indica el último sueldo mensual ordinario.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,2})?")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("UltimoSueldoMensOrd")]
        public decimal UltimoSueldoMensOrd { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar los ingresos acumulables.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar los ingresos acumulables.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,2})?")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("IngresoAcumulable")]
        public decimal IngresoAcumulable { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido que indica los ingresos no acumulables.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido que indica los ingresos no acumulables.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,2})?")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("IngresoNoAcumulable")]
        public decimal IngresoNoAcumulable { get; set; }
    }
}
