//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/nomina=Nomina.v12 resources/sitio_internet/cfd/nomina/nomina12.xsd
namespace JAMS.SAT.CFDI.Xml.Nomina12
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("NominaPercepcionesPercepcionHorasExtra", Namespace="http://www.sat.gob.mx/nomina12", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class NominaPercepcionesPercepcionHorasExtra
    {
        
        /// <summary>
        /// <para>Atributo requerido para expresar el número de días en que el trabajador realizó horas extra en el periodo.</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el número de días en que el trabajador realizó h" +
            "oras extra en el periodo.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Dias")]
        public int Dias { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el tipo de pago de las horas extra.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el tipo de pago de las horas extra.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TipoHoras")]
        public string TipoHoras { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el número de horas extra trabajadas en el periodo.</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el número de horas extra trabajadas en el period" +
            "o.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("HorasExtra")]
        public int HorasExtra { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el importe pagado por las horas extra.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el importe pagado por las horas extra.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,2})?")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("ImportePagado")]
        public decimal ImportePagado { get; set; }
    }
}
