//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/nomina=Nomina.v12 resources/sitio_internet/cfd/nomina/nomina12.xsd
namespace JAMS.SAT.CFDI.Xml.Nomina12
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("NominaIncapacidadesIncapacidad", Namespace="http://www.sat.gob.mx/nomina12", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class NominaIncapacidadesIncapacidad
    {
        
        /// <summary>
        /// <para>Atributo requerido para expresar el número de días enteros que el trabajador se incapacitó en el periodo.</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el número de días enteros que el trabajador se i" +
            "ncapacitó en el periodo.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("DiasIncapacidad")]
        public int DiasIncapacidad { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar la razón de la incapacidad.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar la razón de la incapacidad.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TipoIncapacidad")]
        public string TipoIncapacidad { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el monto del importe monetario de la incapacidad.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar el monto del importe monetario de la incapacid" +
            "ad.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,2})?")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("ImporteMonetario")]
        public decimal ImporteMonetarioValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ImporteMonetario property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool ImporteMonetarioValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el monto del importe monetario de la incapacidad.</para>
        /// <para>Tipo definido para expresar importes monetarios en moneda nacional MXN con fracción hasta dos decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.00.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,2})?.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<decimal> ImporteMonetario
        {
            get
            {
                if (this.ImporteMonetarioValueSpecified)
                {
                    return this.ImporteMonetarioValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ImporteMonetarioValue = value.GetValueOrDefault();
                this.ImporteMonetarioValueSpecified = value.HasValue;
            }
        }
    }
}
