//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/Pagos20=Pagos.v20 resources/sitio_internet/cfd/Pagos/Pagos20.xsd
namespace JAMS.SAT.CFDI.Xml.Pagos.v20
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PagosPagoDoctoRelacionadoImpuestosDrRetencionesDrRetencionDr", Namespace="http://www.sat.gob.mx/Pagos20", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PagosPagoDoctoRelacionadoImpuestosDrRetencionesDrRetencionDr
    {
        
        /// <summary>
        /// <para>Atributo requerido para señalar la base para el cálculo de la retención conforme al monto del pago, aplicable al documento relacionado, la determinación de la base se realiza de acuerdo con las disposiciones fiscales vigentes. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.000001.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo requerido para señalar la base para el cálculo de la retención conforme al monto del pago, aplicable al documento relacionado, la determinación de la base se realiza de acuerdo con las disposiciones fiscales vigentes. No se permiten valores negativos.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("BaseDR")]
        public decimal BaseDr { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para señalar la clave del tipo de impuesto retenido conforme al monto del pago, aplicable al documento relacionado.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para señalar la clave del tipo de impuesto retenido conforme a" +
            "l monto del pago, aplicable al documento relacionado.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("ImpuestoDR")]
        public string ImpuestoDr { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para señalar la clave del tipo de factor que se aplica a la base del impuesto.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para señalar la clave del tipo de factor que se aplica a la ba" +
            "se del impuesto.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TipoFactorDR")]
        public string TipoFactorDr { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para señalar el valor de la tasa o cuota del impuesto que se retiene.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.000000.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para señalar el valor de la tasa o cuota del impuesto que se r" +
            "etiene.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TasaOCuotaDR")]
        public decimal TasaOCuotaDr { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para señalar el importe del impuesto retenido conforme al monto del pago, aplicable al documento relacionado. No se permiten valores negativos.</para>
        /// <para>Tipo definido para expresar importes numéricos con fracción hasta seis decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.000000.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,6})?.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para señalar el importe del impuesto retenido conforme al mont" +
            "o del pago, aplicable al documento relacionado. No se permiten valores negativos" +
            ".")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,6})?")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("ImporteDR")]
        public decimal ImporteDr { get; set; }
    }
}
