//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/Pagos20=Pagos.v20 resources/sitio_internet/cfd/Pagos/Pagos20.xsd
namespace JAMS.SAT.CFDI.Xml.Pagos.v20
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PagosPagoImpuestosPRetencionesP", Namespace="http://www.sat.gob.mx/Pagos20", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PagosPagoImpuestosPRetencionesP
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PagosPagoImpuestosPRetencionesPRetencionP> _retencionP;
        
        /// <summary>
        /// <para>Nodo requerido para señalar la información detallada de una retención de impuesto específico conforme al monto del pago recibido.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para señalar la información detallada de una retención de impuesto" +
            " específico conforme al monto del pago recibido.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("RetencionP")]
        public Collection<PagosPagoImpuestosPRetencionesPRetencionP> RetencionP
        {
            get
            {
                return _retencionP;
            }
            private set
            {
                _retencionP = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PagosPagoImpuestosPRetencionesP" /> class.</para>
        /// </summary>
        public PagosPagoImpuestosPRetencionesP()
        {
            this._retencionP = new Collection<PagosPagoImpuestosPRetencionesPRetencionP>();
        }
    }
}
