//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/Pagos20=Pagos.v20 resources/sitio_internet/cfd/Pagos/Pagos20.xsd
namespace JAMS.SAT.CFDI.Xml.Pagos.v20
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Complemento para el Comprobante Fiscal Digital por Internet (CFDI) para registrar información sobre la recepción de pagos. El emisor de este complemento para recepción de pagos debe ser quien las leyes le obligue a expedir comprobantes por los actos o actividades que realicen, por los ingresos que se perciban o por las retenciones de contribuciones que efectúen.</para>
    /// </summary>
    [DescriptionAttribute(@"Complemento para el Comprobante Fiscal Digital por Internet (CFDI) para registrar información sobre la recepción de pagos. El emisor de este complemento para recepción de pagos debe ser quien las leyes le obligue a expedir comprobantes por los actos o actividades que realicen, por los ingresos que se perciban o por las retenciones de contribuciones que efectúen.")]
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Pagos", Namespace="http://www.sat.gob.mx/Pagos20", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("Pagos", Namespace="http://www.sat.gob.mx/Pagos20")]
    public partial class Pagos
    {
        
        /// <summary>
        /// <para>Nodo requerido para especificar el monto total de los pagos y el total de los impuestos, deben ser expresados en MXN.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para especificar el monto total de los pagos y el total de los imp" +
            "uestos, deben ser expresados en MXN.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Totales")]
        public PagosTotales Totales { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<PagosPago> _pago;
        
        /// <summary>
        /// <para>Elemento requerido para incorporar la información de la recepción de pagos.</para>
        /// </summary>
        [DescriptionAttribute("Elemento requerido para incorporar la información de la recepción de pagos.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Pago")]
        public Collection<PagosPago> Pago
        {
            get
            {
                return _pago;
            }
            private set
            {
                _pago = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Pagos" /> class.</para>
        /// </summary>
        public Pagos()
        {
            this._pago = new Collection<PagosPago>();
        }
        
        [XmlIgnoreAttribute()]
        private string _version = "2.0";
        
        /// <summary>
        /// <para>Atributo requerido que indica la versión del complemento para recepción de pagos.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido que indica la versión del complemento para recepción de pagos." +
            "")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
    }
}
