//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/ine=INE.v11 resources/sitio_internet/cfd/ine/ine11.xsd
namespace JAMS.SAT.CFDI.Xml.INE.v11
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Complemento al Comprobante Fiscal Digital por Internet (CFDI) para incluir los datos que identifiquen el tipo de proceso al que van dirigidos los gastos que realizan los partidos o las Asociaciones Civiles.</para>
    /// </summary>
    [DescriptionAttribute("Complemento al Comprobante Fiscal Digital por Internet (CFDI) para incluir los da" +
        "tos que identifiquen el tipo de proceso al que van dirigidos los gastos que real" +
        "izan los partidos o las Asociaciones Civiles.")]
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("INE", Namespace="http://www.sat.gob.mx/ine", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("INE", Namespace="http://www.sat.gob.mx/ine")]
    public partial class Ine
    {
        
        [XmlIgnoreAttribute()]
        private Collection<IneEntidad> _entidad;
        
        /// <summary>
        /// <para>Nodo condicional para expresar los datos correspondientes a las entidades federativas o circunscripciones en las que se va a aplicar el gasto.</para>
        /// </summary>
        [DescriptionAttribute("Nodo condicional para expresar los datos correspondientes a las entidades federat" +
            "ivas o circunscripciones en las que se va a aplicar el gasto.")]
        [XmlElementAttribute("Entidad")]
        public Collection<IneEntidad> Entidad
        {
            get
            {
                return _entidad;
            }
            private set
            {
                _entidad = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Entidad collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool EntidadSpecified
        {
            get
            {
                return (this.Entidad.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Ine" /> class.</para>
        /// </summary>
        public Ine()
        {
            this._entidad = new Collection<IneEntidad>();
        }
        
        [XmlIgnoreAttribute()]
        private string _version = "1.1";
        
        /// <summary>
        /// <para>Atributo requerido que indica la versión del complemento.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido que indica la versión del complemento.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el tipo de proceso de que se trate.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el tipo de proceso de que se trate.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TipoProceso")]
        public string TipoProceso { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar el tipo de comité de que se trate.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar el tipo de comité de que se trate.")]
        [XmlAttributeAttribute("TipoComite")]
        public string TipoComite { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar la clave de contabilidad de aspirantes precandidatos, candidatos y concentradoras, si se trata de un tipo de proceso ordinario y un comité ejecutivo nacional.Para los otros casos, la clave de contabilidad se registra en el atributo ine:Entidad:Contabilidad:IdContabilidad.</para>
        /// <para xml:lang="en">Total number of digits: 6.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 0.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo opcional para registrar la clave de contabilidad de aspirantes precandidatos, candidatos y concentradoras, si se trata de un tipo de proceso ordinario y un comité ejecutivo nacional.Para los otros casos, la clave de contabilidad se registra en el atributo ine:Entidad:Contabilidad:IdContabilidad.")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("IdContabilidad")]
        public int IdContabilidadValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IdContabilidad property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool IdContabilidadValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar la clave de contabilidad de aspirantes precandidatos, candidatos y concentradoras, si se trata de un tipo de proceso ordinario y un comité ejecutivo nacional.Para los otros casos, la clave de contabilidad se registra en el atributo ine:Entidad:Contabilidad:IdContabilidad.</para>
        /// <para xml:lang="en">Total number of digits: 6.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 0.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<int> IdContabilidad
        {
            get
            {
                if (this.IdContabilidadValueSpecified)
                {
                    return this.IdContabilidadValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IdContabilidadValue = value.GetValueOrDefault();
                this.IdContabilidadValueSpecified = value.HasValue;
            }
        }
    }
}
