//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/TimbreFiscalDigital=TFD.v11 resources/sitio_internet/cfd/TimbreFiscalDigital/TimbreFiscalDigitalv11.xsd
namespace JAMS.SAT.CFDI.Xml.TFD.v11
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Complemento requerido para el Timbrado Fiscal Digital que da validez al Comprobante fiscal digital por Internet.</para>
    /// </summary>
    [DescriptionAttribute("Complemento requerido para el Timbrado Fiscal Digital que da validez al Comproban" +
        "te fiscal digital por Internet.")]
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("TimbreFiscalDigital", Namespace="http://www.sat.gob.mx/TimbreFiscalDigital", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("TimbreFiscalDigital", Namespace="http://www.sat.gob.mx/TimbreFiscalDigital")]
    public partial class TimbreFiscalDigital
    {
        
        [XmlIgnoreAttribute()]
        private string _version = "1.1";
        
        /// <summary>
        /// <para>Atributo requerido para la expresión de la versión del estándar del Timbre Fiscal Digital</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para la expresión de la versión del estándar del Timbre Fiscal" +
            " Digital")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
        
        /// <summary>
        /// <para>Atributo requerido para expresar los 36 caracteres del folio fiscal (UUID) de la transacción de timbrado conforme al estándar RFC 4122</para>
        /// <para xml:lang="en">Minimum length: 36.</para>
        /// <para xml:lang="en">Maximum length: 36.</para>
        /// <para xml:lang="en">Pattern: [a-f0-9A-F]{8}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{12}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar los 36 caracteres del folio fiscal (UUID) de la " +
            "transacción de timbrado conforme al estándar RFC 4122")]
        [MinLengthAttribute(36)]
        [MaxLengthAttribute(36)]
        [RegularExpressionAttribute("[a-f0-9A-F]{8}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{12}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("UUID")]
        public string Uuid { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar la fecha y hora, de la generación del timbre por la certificación digital del SAT. Se expresa en la forma AAAA-MM-DDThh:mm:ss y debe corresponder con la hora de la Zona Centro del Sistema de Horario en México.</para>
        /// <para>Tipo definido para la expresión de la fecha y hora. Se expresa en la forma AAAA-MM-DDThh:mm:ss</para>
        /// <para xml:lang="en">Pattern: (20[1-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]).</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar la fecha y hora, de la generación del timbre por" +
            " la certificación digital del SAT. Se expresa en la forma AAAA-MM-DDThh:mm:ss y " +
            "debe corresponder con la hora de la Zona Centro del Sistema de Horario en México" +
            ".")]
        [RegularExpressionAttribute("(20[1-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5]" +
            "[0-9]:[0-5][0-9])")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("FechaTimbrado", DataType="dateTime")]
        public DateTime FechaTimbrado { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el RFC del proveedor de certificación de comprobantes fiscales digitales que genera el timbre fiscal digital.</para>
        /// <para>Tipo definido para la expresión de un Registro Federal de Contribuyentes de persona moral.</para>
        /// <para xml:lang="en">Minimum length: 12.</para>
        /// <para xml:lang="en">Pattern: [A-Z&Ñ]{3}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A].</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el RFC del proveedor de certificación de comprob" +
            "antes fiscales digitales que genera el timbre fiscal digital.")]
        [MinLengthAttribute(12)]
        [RegularExpressionAttribute("[A-Z&Ñ]{3}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A]")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("RfcProvCertif")]
        public string RfcProvCertif { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para registrar información que el SAT comunique a los usuarios del CFDI.</para>
        /// <para xml:lang="en">Minimum length: 12.</para>
        /// <para xml:lang="en">Maximum length: 150.</para>
        /// <para xml:lang="en">Pattern: ([A-Z]|[a-z]|[0-9]| |Ñ|ñ|!|"|%|&|'|´|-|:|;|>|=|<|@|_|,|\{|\}|`|~|á|é|í|ó|ú|Á|É|Í|Ó|Ú|ü|Ü){1,150}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para registrar información que el SAT comunique a los usuarios " +
            "del CFDI.")]
        [MinLengthAttribute(12)]
        [MaxLengthAttribute(150)]
        [RegularExpressionAttribute("([A-Z]|[a-z]|[0-9]| |Ñ|ñ|!|\"|%|&|\'|´|-|:|;|>|=|<|@|_|,|\\{|\\}|`|~|á|é|í|ó|ú|Á|É|Í|" +
            "Ó|Ú|ü|Ü){1,150}")]
        [XmlAttributeAttribute("Leyenda")]
        public string Leyenda { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para contener el sello digital del comprobante fiscal o del comprobante de retenciones, que se ha timbrado. El sello debe ser expresado como una cadena de texto en formato Base 64.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para contener el sello digital del comprobante fiscal o del co" +
            "mprobante de retenciones, que se ha timbrado. El sello debe ser expresado como u" +
            "na cadena de texto en formato Base 64.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("SelloCFD")]
        public string SelloCfd { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el número de serie del certificado del SAT usado para generar el sello digital del Timbre Fiscal Digital.</para>
        /// <para xml:lang="en">Minimum length: 20.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// <para xml:lang="en">Pattern: [0-9]{20}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el número de serie del certificado del SAT usado" +
            " para generar el sello digital del Timbre Fiscal Digital.")]
        [MinLengthAttribute(20)]
        [MaxLengthAttribute(20)]
        [RegularExpressionAttribute("[0-9]{20}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("NoCertificadoSAT")]
        public string NoCertificadoSat { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para contener el sello digital del Timbre Fiscal Digital, al que hacen referencia las reglas de la Resolución Miscelánea vigente. El sello debe ser expresado como una cadena de texto en formato Base 64.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para contener el sello digital del Timbre Fiscal Digital, al q" +
            "ue hacen referencia las reglas de la Resolución Miscelánea vigente. El sello deb" +
            "e ser expresado como una cadena de texto en formato Base 64.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("SelloSAT")]
        public string SelloSat { get; set; }
    }
}
