//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/cfd/4=v40 resources/sitio_internet/cfd/4/cfdv40.xsd
namespace JAMS.SAT.CFDI.Xml.v40
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ComprobanteConceptosConceptoCuentaPredial", Namespace="http://www.sat.gob.mx/cfd/4", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ComprobanteConceptosConceptoCuentaPredial
    {
        
        /// <summary>
        /// <para>Atributo requerido para precisar el número de la cuenta predial del inmueble cubierto por el presente concepto, o bien para incorporar los datos de identificación del certificado de participación inmobiliaria no amortizable, tratándose de arrendamiento.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 150.</para>
        /// <para xml:lang="en">Pattern: [0-9a-zA-Z]{1,150}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para precisar el número de la cuenta predial del inmueble cubi" +
            "erto por el presente concepto, o bien para incorporar los datos de identificació" +
            "n del certificado de participación inmobiliaria no amortizable, tratándose de ar" +
            "rendamiento.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(150)]
        [RegularExpressionAttribute("[0-9a-zA-Z]{1,150}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Numero")]
        public string Numero { get; set; }
    }
}
