//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/cfd/4=v40 resources/sitio_internet/cfd/4/cfdv40.xsd
namespace JAMS.SAT.CFDI.Xml.v40
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ComprobanteConceptosConceptoImpuestos", Namespace="http://www.sat.gob.mx/cfd/4", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ComprobanteConceptosConceptoImpuestos
    {
        
        [XmlIgnoreAttribute()]
        private Collection<ComprobanteConceptosConceptoImpuestosTrasladosTraslado> _traslados;
        
        /// <summary>
        /// <para>Nodo opcional para asentar los impuestos trasladados aplicables al presente concepto.</para>
        /// </summary>
        [DescriptionAttribute("Nodo opcional para asentar los impuestos trasladados aplicables al presente conce" +
            "pto.")]
        [XmlArrayAttribute("Traslados")]
        [XmlArrayItemAttribute("Traslado", Namespace="http://www.sat.gob.mx/cfd/4")]
        public Collection<ComprobanteConceptosConceptoImpuestosTrasladosTraslado> Traslados
        {
            get
            {
                return _traslados;
            }
            private set
            {
                _traslados = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Traslados collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool TrasladosSpecified
        {
            get
            {
                return (this.Traslados.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ComprobanteConceptosConceptoImpuestos" /> class.</para>
        /// </summary>
        public ComprobanteConceptosConceptoImpuestos()
        {
            this._traslados = new Collection<ComprobanteConceptosConceptoImpuestosTrasladosTraslado>();
            this._retenciones = new Collection<ComprobanteConceptosConceptoImpuestosRetencionesRetencion>();
        }
        
        [XmlIgnoreAttribute()]
        private Collection<ComprobanteConceptosConceptoImpuestosRetencionesRetencion> _retenciones;
        
        /// <summary>
        /// <para>Nodo opcional para asentar los impuestos retenidos aplicables al presente concepto.</para>
        /// </summary>
        [DescriptionAttribute("Nodo opcional para asentar los impuestos retenidos aplicables al presente concept" +
            "o.")]
        [XmlArrayAttribute("Retenciones")]
        [XmlArrayItemAttribute("Retencion", Namespace="http://www.sat.gob.mx/cfd/4")]
        public Collection<ComprobanteConceptosConceptoImpuestosRetencionesRetencion> Retenciones
        {
            get
            {
                return _retenciones;
            }
            private set
            {
                _retenciones = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Retenciones collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool RetencionesSpecified
        {
            get
            {
                return (this.Retenciones.Count != 0);
            }
        }
    }
}
