//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/cfd/4=v40 resources/sitio_internet/cfd/4/cfdv40.xsd
namespace JAMS.SAT.CFDI.Xml.v40
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ComprobanteConceptosConceptoImpuestosRetenciones", Namespace="http://www.sat.gob.mx/cfd/4", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ComprobanteConceptosConceptoImpuestosRetenciones
    {
        
        [XmlIgnoreAttribute()]
        private Collection<ComprobanteConceptosConceptoImpuestosRetencionesRetencion> _retencion;
        
        /// <summary>
        /// <para>Nodo requerido para asentar la información detallada de una retención de impuestos aplicable al presente concepto.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para asentar la información detallada de una retención de impuesto" +
            "s aplicable al presente concepto.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Retencion")]
        public Collection<ComprobanteConceptosConceptoImpuestosRetencionesRetencion> Retencion
        {
            get
            {
                return _retencion;
            }
            private set
            {
                _retencion = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ComprobanteConceptosConceptoImpuestosRetenciones" /> class.</para>
        /// </summary>
        public ComprobanteConceptosConceptoImpuestosRetenciones()
        {
            this._retencion = new Collection<ComprobanteConceptosConceptoImpuestosRetencionesRetencion>();
        }
    }
}
