//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/cfd/4=v40 resources/sitio_internet/cfd/4/cfdv40.xsd
namespace JAMS.SAT.CFDI.Xml.v40
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ComprobanteInformacionGlobal", Namespace="http://www.sat.gob.mx/cfd/4", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ComprobanteInformacionGlobal
    {
        
        /// <summary>
        /// <para>Atributo requerido para expresar el período al que corresponde la información del comprobante global.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el período al que corresponde la información del" +
            " comprobante global.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Periodicidad")]
        public string Periodicidad { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el mes o los meses al que corresponde la información del comprobante global.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el mes o los meses al que corresponde la informa" +
            "ción del comprobante global.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Meses")]
        public string Meses { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el año al que corresponde la información del comprobante global.</para>
        /// <para xml:lang="en">Minimum inclusive value: 2021.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el año al que corresponde la información del com" +
            "probante global.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Año")]
        public short Año { get; set; }
    }
}
