//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/cfd/4=v40 resources/sitio_internet/cfd/4/cfdv40.xsd
namespace JAMS.SAT.CFDI.Xml.v40
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Estándar de Comprobante Fiscal Digital por Internet.</para>
    /// </summary>
    [DescriptionAttribute("Estándar de Comprobante Fiscal Digital por Internet.")]
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Comprobante", Namespace="http://www.sat.gob.mx/cfd/4", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("Comprobante", Namespace="http://www.sat.gob.mx/cfd/4")]
    public partial class Comprobante
    {
        
        /// <summary>
        /// <para>Nodo condicional para precisar la información relacionada con el comprobante global.</para>
        /// </summary>
        [DescriptionAttribute("Nodo condicional para precisar la información relacionada con el comprobante glob" +
            "al.")]
        [XmlElementAttribute("InformacionGlobal")]
        public ComprobanteInformacionGlobal InformacionGlobal { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<ComprobanteCfdiRelacionados> _cfdiRelacionados;
        
        /// <summary>
        /// <para>Nodo opcional para precisar la información de los comprobantes relacionados.</para>
        /// </summary>
        [DescriptionAttribute("Nodo opcional para precisar la información de los comprobantes relacionados.")]
        [XmlElementAttribute("CfdiRelacionados")]
        public Collection<ComprobanteCfdiRelacionados> CfdiRelacionados
        {
            get
            {
                return _cfdiRelacionados;
            }
            private set
            {
                _cfdiRelacionados = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the CfdiRelacionados collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool CfdiRelacionadosSpecified
        {
            get
            {
                return (this.CfdiRelacionados.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Comprobante" /> class.</para>
        /// </summary>
        public Comprobante()
        {
            this._cfdiRelacionados = new Collection<ComprobanteCfdiRelacionados>();
            this._conceptos = new Collection<ComprobanteConceptosConcepto>();
        }
        
        /// <summary>
        /// <para>Nodo requerido para expresar la información del contribuyente emisor del comprobante.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para expresar la información del contribuyente emisor del comproba" +
            "nte.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Emisor")]
        public ComprobanteEmisor Emisor { get; set; }
        
        /// <summary>
        /// <para>Nodo requerido para precisar la información del contribuyente receptor del comprobante.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para precisar la información del contribuyente receptor del compro" +
            "bante.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Receptor")]
        public ComprobanteReceptor Receptor { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<ComprobanteConceptosConcepto> _conceptos;
        
        /// <summary>
        /// <para>Nodo requerido para listar los conceptos cubiertos por el comprobante.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para listar los conceptos cubiertos por el comprobante.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlArrayAttribute("Conceptos")]
        [XmlArrayItemAttribute("Concepto", Namespace="http://www.sat.gob.mx/cfd/4")]
        public Collection<ComprobanteConceptosConcepto> Conceptos
        {
            get
            {
                return _conceptos;
            }
            private set
            {
                _conceptos = value;
            }
        }
        
        /// <summary>
        /// <para>Nodo condicional para expresar el resumen de los impuestos aplicables.</para>
        /// </summary>
        [DescriptionAttribute("Nodo condicional para expresar el resumen de los impuestos aplicables.")]
        [XmlElementAttribute("Impuestos")]
        public ComprobanteImpuestos Impuestos { get; set; }
        
        /// <summary>
        /// <para>Nodo opcional donde se incluye el complemento Timbre Fiscal Digital de manera obligatoria y los nodos complementarios determinados por el SAT, de acuerdo con las disposiciones particulares para un sector o actividad específica.</para>
        /// </summary>
        [DescriptionAttribute("Nodo opcional donde se incluye el complemento Timbre Fiscal Digital de manera obl" +
            "igatoria y los nodos complementarios determinados por el SAT, de acuerdo con las" +
            " disposiciones particulares para un sector o actividad específica.")]
        [XmlElementAttribute("Complemento")]
        public ComprobanteComplemento Complemento { get; set; }
        
        /// <summary>
        /// <para>Nodo opcional para recibir las extensiones al presente formato que sean de utilidad al contribuyente. Para las reglas de uso del mismo, referirse al formato origen.</para>
        /// </summary>
        [DescriptionAttribute("Nodo opcional para recibir las extensiones al presente formato que sean de utilid" +
            "ad al contribuyente. Para las reglas de uso del mismo, referirse al formato orig" +
            "en.")]
        [XmlElementAttribute("Addenda")]
        public ComprobanteAddenda Addenda { get; set; }
        
        [XmlIgnoreAttribute()]
        private string _version = "4.0";
        
        /// <summary>
        /// <para>Atributo requerido con valor prefijado a 4.0 que indica la versión del estándar bajo el que se encuentra expresado el comprobante.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido con valor prefijado a 4.0 que indica la versión del estándar b" +
            "ajo el que se encuentra expresado el comprobante.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
        
        /// <summary>
        /// <para>Atributo opcional para precisar la serie para control interno del contribuyente. Este atributo acepta una cadena de caracteres.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 25.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,25}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para precisar la serie para control interno del contribuyente. " +
            "Este atributo acepta una cadena de caracteres.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(25)]
        [RegularExpressionAttribute("[^|]{1,25}")]
        [XmlAttributeAttribute("Serie")]
        public string Serie { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para control interno del contribuyente que expresa el folio del comprobante, acepta una cadena de caracteres.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 40.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,40}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para control interno del contribuyente que expresa el folio del" +
            " comprobante, acepta una cadena de caracteres.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(40)]
        [RegularExpressionAttribute("[^|]{1,40}")]
        [XmlAttributeAttribute("Folio")]
        public string Folio { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para la expresión de la fecha y hora de expedición del Comprobante Fiscal Digital por Internet. Se expresa en la forma AAAA-MM-DDThh:mm:ss y debe corresponder con la hora local donde se expide el comprobante.</para>
        /// <para>Tipo definido para la expresión de la fecha y hora. Se expresa en la forma AAAA-MM-DDThh:mm:ss</para>
        /// <para xml:lang="en">Pattern: (20[1-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]).</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para la expresión de la fecha y hora de expedición del Comprob" +
            "ante Fiscal Digital por Internet. Se expresa en la forma AAAA-MM-DDThh:mm:ss y d" +
            "ebe corresponder con la hora local donde se expide el comprobante.")]
        [RegularExpressionAttribute("(20[1-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5]" +
            "[0-9]:[0-5][0-9])")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Fecha", DataType="dateTime")]
        public DateTime Fecha { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para contener el sello digital del comprobante fiscal, al que hacen referencia las reglas de resolución miscelánea vigente. El sello debe ser expresado como una cadena de texto en formato Base 64.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para contener el sello digital del comprobante fiscal, al que " +
            "hacen referencia las reglas de resolución miscelánea vigente. El sello debe ser " +
            "expresado como una cadena de texto en formato Base 64.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Sello")]
        public string Sello { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar la clave de la forma de pago de los bienes o servicios amparados por el comprobante.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar la clave de la forma de pago de los bienes o s" +
            "ervicios amparados por el comprobante.")]
        [XmlAttributeAttribute("FormaPago")]
        public string FormaPago { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar el número de serie del certificado de sello digital que ampara al comprobante, de acuerdo con el acuse correspondiente a 20 posiciones otorgado por el sistema del SAT.</para>
        /// <para xml:lang="en">Minimum length: 20.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// <para xml:lang="en">Pattern: [0-9]{20}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar el número de serie del certificado de sello digi" +
            "tal que ampara al comprobante, de acuerdo con el acuse correspondiente a 20 posi" +
            "ciones otorgado por el sistema del SAT.")]
        [MinLengthAttribute(20)]
        [MaxLengthAttribute(20)]
        [RegularExpressionAttribute("[0-9]{20}")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("NoCertificado")]
        public string NoCertificado { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido que sirve para incorporar el certificado de sello digital que ampara al comprobante, como texto en formato base 64.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido que sirve para incorporar el certificado de sello digital que " +
            "ampara al comprobante, como texto en formato base 64.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Certificado")]
        public string Certificado { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para expresar las condiciones comerciales aplicables para el pago del comprobante fiscal digital por Internet. Este atributo puede ser condicionado mediante atributos o complementos.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1000.</para>
        /// <para xml:lang="en">Pattern: [^|]{1,1000}.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para expresar las condiciones comerciales aplicables para el" +
            " pago del comprobante fiscal digital por Internet. Este atributo puede ser condi" +
            "cionado mediante atributos o complementos.")]
        [MinLengthAttribute(1)]
        [MaxLengthAttribute(1000)]
        [RegularExpressionAttribute("[^|]{1,1000}")]
        [XmlAttributeAttribute("CondicionesDePago")]
        public string CondicionesDePago { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para representar la suma de los importes de los conceptos antes de descuentos e impuesto. No se permiten valores negativos.</para>
        /// <para>Tipo definido para expresar importes numéricos con fracción hasta seis decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.000000.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,6})?.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para representar la suma de los importes de los conceptos ante" +
            "s de descuentos e impuesto. No se permiten valores negativos.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,6})?")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("SubTotal")]
        public decimal SubTotal { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para representar el importe total de los descuentos aplicables antes de impuestos. No se permiten valores negativos. Se debe registrar cuando existan conceptos con descuento.</para>
        /// <para>Tipo definido para expresar importes numéricos con fracción hasta seis decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.000000.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,6})?.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para representar el importe total de los descuentos aplicabl" +
            "es antes de impuestos. No se permiten valores negativos. Se debe registrar cuand" +
            "o existan conceptos con descuento.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,6})?")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("Descuento")]
        public decimal DescuentoValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Descuento property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool DescuentoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para representar el importe total de los descuentos aplicables antes de impuestos. No se permiten valores negativos. Se debe registrar cuando existan conceptos con descuento.</para>
        /// <para>Tipo definido para expresar importes numéricos con fracción hasta seis decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.000000.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,6})?.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<decimal> Descuento
        {
            get
            {
                if (this.DescuentoValueSpecified)
                {
                    return this.DescuentoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DescuentoValue = value.GetValueOrDefault();
                this.DescuentoValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Atributo requerido para identificar la clave de la moneda utilizada para expresar los montos, cuando se usa moneda nacional se registra MXN. Conforme con la especificación ISO 4217.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para identificar la clave de la moneda utilizada para expresar" +
            " los montos, cuando se usa moneda nacional se registra MXN. Conforme con la espe" +
            "cificación ISO 4217.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Moneda")]
        public string Moneda { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para representar el tipo de cambio FIX conforme con la moneda usada. Es requerido cuando la clave de moneda es distinta de MXN y de XXX. El valor debe reflejar el número de pesos mexicanos que equivalen a una unidad de la divisa señalada en el atributo moneda. Si el valor está fuera del porcentaje aplicable a la moneda tomado del catálogo c_Moneda, el emisor debe obtener del PAC que vaya a timbrar el CFDI, de manera no automática, una clave de confirmación para ratificar que el valor es correcto e integrar dicha clave en el atributo Confirmacion.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.000001.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para representar el tipo de cambio FIX conforme con la moneda usada. Es requerido cuando la clave de moneda es distinta de MXN y de XXX. El valor debe reflejar el número de pesos mexicanos que equivalen a una unidad de la divisa señalada en el atributo moneda. Si el valor está fuera del porcentaje aplicable a la moneda tomado del catálogo c_Moneda, el emisor debe obtener del PAC que vaya a timbrar el CFDI, de manera no automática, una clave de confirmación para ratificar que el valor es correcto e integrar dicha clave en el atributo Confirmacion.")]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [XmlAttributeAttribute("TipoCambio")]
        public decimal TipoCambioValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TipoCambio property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool TipoCambioValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para representar el tipo de cambio FIX conforme con la moneda usada. Es requerido cuando la clave de moneda es distinta de MXN y de XXX. El valor debe reflejar el número de pesos mexicanos que equivalen a una unidad de la divisa señalada en el atributo moneda. Si el valor está fuera del porcentaje aplicable a la moneda tomado del catálogo c_Moneda, el emisor debe obtener del PAC que vaya a timbrar el CFDI, de manera no automática, una clave de confirmación para ratificar que el valor es correcto e integrar dicha clave en el atributo Confirmacion.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.000001.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public Nullable<decimal> TipoCambio
        {
            get
            {
                if (this.TipoCambioValueSpecified)
                {
                    return this.TipoCambioValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TipoCambioValue = value.GetValueOrDefault();
                this.TipoCambioValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Atributo requerido para representar la suma del subtotal, menos los descuentos aplicables, más las contribuciones recibidas (impuestos trasladados - federales y/o locales, derechos, productos, aprovechamientos, aportaciones de seguridad social, contribuciones de mejoras) menos los impuestos retenidos federales y/o locales. Si el valor es superior al límite que establezca el SAT en la Resolución Miscelánea Fiscal vigente, el emisor debe obtener del PAC que vaya a timbrar el CFDI, de manera no automática, una clave de confirmación para ratificar que el valor es correcto e integrar dicha clave en el atributo Confirmacion. No se permiten valores negativos.</para>
        /// <para>Tipo definido para expresar importes numéricos con fracción hasta seis decimales. No se permiten valores negativos.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.000000.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,18}(.[0-9]{1,6})?.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo requerido para representar la suma del subtotal, menos los descuentos aplicables, más las contribuciones recibidas (impuestos trasladados - federales y/o locales, derechos, productos, aprovechamientos, aportaciones de seguridad social, contribuciones de mejoras) menos los impuestos retenidos federales y/o locales. Si el valor es superior al límite que establezca el SAT en la Resolución Miscelánea Fiscal vigente, el emisor debe obtener del PAC que vaya a timbrar el CFDI, de manera no automática, una clave de confirmación para ratificar que el valor es correcto e integrar dicha clave en el atributo Confirmacion. No se permiten valores negativos.")]
        [RegularExpressionAttribute("[0-9]{1,18}(.[0-9]{1,6})?")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Total")]
        public decimal Total { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar la clave del efecto del comprobante fiscal para el contribuyente emisor.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar la clave del efecto del comprobante fiscal para " +
            "el contribuyente emisor.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("TipoDeComprobante")]
        public string TipoDeComprobante { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para expresar si el comprobante ampara una operación de exportación.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para expresar si el comprobante ampara una operación de export" +
            "ación.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("Exportacion")]
        public string Exportacion { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para precisar la clave del método de pago que aplica para este comprobante fiscal digital por Internet, conforme al Artículo 29-A fracción VII incisos a y b del CFF.</para>
        /// </summary>
        [DescriptionAttribute("Atributo condicional para precisar la clave del método de pago que aplica para es" +
            "te comprobante fiscal digital por Internet, conforme al Artículo 29-A fracción V" +
            "II incisos a y b del CFF.")]
        [XmlAttributeAttribute("MetodoPago")]
        public string MetodoPago { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para incorporar el código postal del lugar de expedición del comprobante (domicilio de la matriz o de la sucursal).</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para incorporar el código postal del lugar de expedición del c" +
            "omprobante (domicilio de la matriz o de la sucursal).")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("LugarExpedicion")]
        public string LugarExpedicion { get; set; }
        
        /// <summary>
        /// <para>Atributo condicional para registrar la clave de confirmación que entregue el PAC para expedir el comprobante con importes grandes, con un tipo de cambio fuera del rango establecido o con ambos casos. Es requerido cuando se registra un tipo de cambio o un total fuera del rango establecido.</para>
        /// <para xml:lang="en">Minimum length: 5.</para>
        /// <para xml:lang="en">Maximum length: 5.</para>
        /// <para xml:lang="en">Pattern: [0-9a-zA-Z]{5}.</para>
        /// </summary>
        [DescriptionAttribute(@"Atributo condicional para registrar la clave de confirmación que entregue el PAC para expedir el comprobante con importes grandes, con un tipo de cambio fuera del rango establecido o con ambos casos. Es requerido cuando se registra un tipo de cambio o un total fuera del rango establecido.")]
        [MinLengthAttribute(5)]
        [MaxLengthAttribute(5)]
        [RegularExpressionAttribute("[0-9a-zA-Z]{5}")]
        [XmlAttributeAttribute("Confirmacion")]
        public string Confirmacion { get; set; }
    }
}
