//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/cfd/4=v40 resources/sitio_internet/cfd/4/cfdv40.xsd
namespace JAMS.SAT.CFDI.Xml.v40
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ComprobanteImpuestosTraslados", Namespace="http://www.sat.gob.mx/cfd/4", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ComprobanteImpuestosTraslados
    {
        
        [XmlIgnoreAttribute()]
        private Collection<ComprobanteImpuestosTrasladosTraslado> _traslado;
        
        /// <summary>
        /// <para>Nodo requerido para la información detallada de un traslado de impuesto específico.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para la información detallada de un traslado de impuesto específic" +
            "o.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Traslado")]
        public Collection<ComprobanteImpuestosTrasladosTraslado> Traslado
        {
            get
            {
                return _traslado;
            }
            private set
            {
                _traslado = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ComprobanteImpuestosTraslados" /> class.</para>
        /// </summary>
        public ComprobanteImpuestosTraslados()
        {
            this._traslado = new Collection<ComprobanteImpuestosTrasladosTraslado>();
        }
    }
}
