//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1160.0 using the following command:
// xscgen -p JAMS.SAT.CFDI.Xml --nullable --nc --cn --sf --nh -v -o XML --enumAsString --namespaceFile=namespaces_mapping.txt -n http://www.sat.gob.mx/ecb=ECB resources/sitio_internet/cfd/ecb/ecb.xsd
namespace JAMS.SAT.CFDI.Xml.ECB
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Complemento al Comprobante Fiscal Digital (CFD) y Comprobante Fiscal Digital a través de Internet (CFDI) para integrar información aplicable al estado de cuenta bancario.</para>
    /// </summary>
    [DescriptionAttribute("Complemento al Comprobante Fiscal Digital (CFD) y Comprobante Fiscal Digital a tr" +
        "avés de Internet (CFDI) para integrar información aplicable al estado de cuenta " +
        "bancario.")]
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1160.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("EstadoDeCuentaBancario", Namespace="http://www.sat.gob.mx/ecb", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("EstadoDeCuentaBancario", Namespace="http://www.sat.gob.mx/ecb")]
    public partial class EstadoDeCuentaBancario
    {
        
        /// <summary>
        /// <para>Nodo requerido para enlistar los conceptos cubiertos por Estado de Cuenta Bancario.</para>
        /// </summary>
        [DescriptionAttribute("Nodo requerido para enlistar los conceptos cubiertos por Estado de Cuenta Bancari" +
            "o.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("Movimientos")]
        public EstadoDeCuentaBancarioMovimientos Movimientos { get; set; }
        
        [XmlIgnoreAttribute()]
        private string _version = "1.0";
        
        /// <summary>
        /// <para>Atributo requerido con valor prefijado a 1.0 que indica la versión del estándar bajo el que se encuentra expresado el complemento al comprobante.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido con valor prefijado a 1.0 que indica la versión del estándar b" +
            "ajo el que se encuentra expresado el complemento al comprobante.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
        
        /// <summary>
        /// <para>Atributo requerido para indicar el número de cuenta del producto bancario.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para indicar el número de cuenta del producto bancario.")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("numeroCuenta")]
        public string NumeroCuenta { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para indicar el nombre del cuentahabiente de la institución bancaria.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para indicar el nombre del cuentahabiente de la institución ba" +
            "ncaria.")]
        [MinLengthAttribute(1)]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("nombreCliente")]
        public string NombreCliente { get; set; }
        
        /// <summary>
        /// <para>Atributo requerido para indicar periodo de los cargos o abonos al instrumento bancario.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// </summary>
        [DescriptionAttribute("Atributo requerido para indicar periodo de los cargos o abonos al instrumento ban" +
            "cario.")]
        [MinLengthAttribute(1)]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("periodo")]
        public string Periodo { get; set; }
        
        /// <summary>
        /// <para>Atributo opcional para indicar la sucursal a la cual pertenece el cuentahabiente.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// </summary>
        [DescriptionAttribute("Atributo opcional para indicar la sucursal a la cual pertenece el cuentahabiente." +
            "")]
        [MinLengthAttribute(1)]
        [XmlAttributeAttribute("sucursal")]
        public string Sucursal { get; set; }
    }
}
